-- * _JOKER_VERSION: 0.0.1 ** Please do not modify this line.
--[[----------------------------------------------------------
	Joker - Jokes, Riddles, Fun Facts, & Other Tomfoolery
  ----------------------------------------------------------
  *
  * ADDING YOUR OWN JOKES:
  * Be aware that modifying this file incorrectly could break Joker,
  * so for normal users I recommend just compiling your jokes in the
  * '_MyCustomJokes.lua' file instead.
  *
  * COMPILATION: Burns / Insults
	*
	* SOURCES:
  * http://pun.me,
  * Reddit Search, 
  * Google Search
	*
]]--

JokerData = JokerData or {}
JokerData.Config = JokerData.Config or {}

JokerData.Config.Burns = {
  command = "burn",
  label = "Burns",
  joke = true,
  nsfw = false,
  usePrefix = true,
  whitelistSlashCommand = true
}

JokerData.Burns = {
  "If laughter is the best medicine, your face must be curing the world.",
  "You're so ugly, you scared the crap out of the toilet.",
  "Your family tree must be a cactus because everybody on it is a prick.",
  "No I'm not insulting you, I'm describing you.",
  "It's better to let someone think you are an idiot than to open your mouth and prove it.",
  "If I had a face like yours, I'd sue my parents.",
  "Your birth certificate is an apology letter from the condom factory.",
  "I guess you prove that even God makes mistakes sometimes.",
  "The only way you'll ever get laid is if you crawl up a chicken's ass and wait.",
  "You're so fake, Barbie is jealous.",
  "I’m jealous of people that don’t know you!",
  "My psychiatrist told me I was crazy and I said I want a second opinion. He said okay, you're ugly too.",
  "You're so ugly, when your mom dropped you off at school she got a fine for littering.",
  "If I wanted to kill myself I'd climb your ego and jump to your IQ.",
  "You must have been born on a highway because that's where most accidents happen.",
  "Brains aren't everything. In your case they're nothing.",
  "I don't know what makes you so stupid, but it really works.",
  "I can explain it to you, but I can't understand it for you.",
  "Roses are red, violets are blue, God made me pretty, what happened to you?",
  "Behind every fat woman there is a beautiful woman. No seriously, you're in the way!",
  "You're like a cloud. When you disappear, it's a beautiful day.",
  "You, sir, are an oxygen thief!",
  "Some babies were dropped on their heads but you were clearly thrown at a wall.",
  "Don't like my sarcasm? Well, I don't like your stupid!",
  "Why don't you go play in traffic?",
  "Please shut your mouth when you're talking to me.",
  "I'd slap you, but that would be animal abuse.",
  "They say opposites attract. I hope you meet someone who is good-looking, intelligent, and cultured.",
  "Stop trying to be a smart ass, you're just an ass.",
  "You're the reason gene pools need lifeguards.",
  "I'm busy now. Can I ignore you some other time?",
  "You have Diarrhea of the mouth; constipation of the ideas.",
  "If ugly were a crime, you'd get a life sentence.",
  "Your mind is on vacation but your mouth is working overtime.",
  "I can lose weight, but you’ll always be ugly.",
  "Why don't you slip into something more comfortable... like a coma.",
  "Shock me, say something intelligent.",
  "If you're gonna be two faced, honey, then at least make one of them pretty.",
  "Keep rolling your eyes, perhaps you'll find a brain back there.",
  "You are not as bad as people say, you are much, much worse.",
  "I don't know what your problem is, but I'll bet it's hard to pronounce.",
  "You get ten times more girls than me? Ten times zero is zero...",
  "There is no vaccine against stupidity.",
  "You're the reason the gene pool needs a lifeguard.",
  "Sure, I've seen people like you before - but I had to pay an admission.",
  "How old are you? - Wait I shouldn't ask, you can't count that high.",
  "You're like a software update. Whenever I see you, I think 'not now'.",
  "You're like Monday mornings, nobody likes you.",
  "Of course I talk like an idiot, how else would you understand me?",
  "You bring everyone so much joy... when you leave the room.",
  "To make you laugh on Saturday, I need to tell you a joke on Wednesday.",
  "You're so fat, you could sell shade.",
  "I'd like to see things from your point of view but I can't seem to get my head that far up my ass.",
  "Don't you need a license to be that ugly?",
  "My friend thinks he is smart. He told me an onion is the only food that makes you cry, so I threw a coconut at his face.",
  "Your house is so dirty you have to wipe your feet before you go outside.",
  "If you really spoke your mind, you'd be speechless.",
  "Stupidity is not a crime so you are free to go.",
  "You are so old, when you were a kid rainbows were black and white.",
  "If I told you that I have a piece of dirt in my eye, would you move?",
  "You so dumb, you think Cheerios are doughnut seeds.",
  "So, a thought crossed your mind? Must have been a long and lonely journey.",
  "You are so old, your birth-certificate expired.",
  "Every time I'm next to you, I get a fierce desire to be alone.",
  "You're so dumb that you got hit by a parked car.",
  "Keep talking, someday you'll say something intelligent!",
  "You're so fat, you leave footprints in concrete.",
  "How did you get here? Did someone leave your cage open?",
  "Pardon me, but you've obviously mistaken me for someone who gives a damn.",
  "Wipe your mouth, there's still a tiny bit of bullshit around your lips.",
  "Don't you have a terribly empty feeling - in your skull?",
  "As an outsider, what do you think of the human race?",
  "Just because you have one doesn't mean you have to act like one.",
  "We can always tell when you are lying. Your lips move.",
  "I'm not saying I hate you, but if you were on fire and I had water, I'd drink it.",
  "You'd need twice the brains to qualify as a half-wit.",
  "You have the face of a saint. A Saint Bernard, that is.",
  "What you lack in intelligence, you more than make up for in stupidity.",
  "You're listed in Who's Who as What's That.",
  "God wasted a good asshole when he put teeth in your mouth.",
  "I couldn't stop thinking about you all day today. I was at the zoo.",
  "Are you always so stupid or is today a special occasion?",
  "You need to shut your mouth 'cause all your stupidity is leaking out.",
  "I'd explain it to you, but I left my crayons at home.",
  "If I had a dollar for every brain cell you have, I'd be in debt.",
  "I heard you were born on a farm. Any more in the litter?",
  "Everyone has the right to be stupid, but you're just abusing the privilege.",
  "I wouldn't pee in your ear if your brain was on fire.",
  "If I had a face like yours, I'd teach my ass to talk.",
  "Don't feel bad. A lot of people have no talent.",
  "I couldn't warm to you if you were on fire.",
  "Just let people think you're an idiot. If you say anything, you'll just prove them right.",
  "As an outsider, what do you think of the human race?",
  "You don't need some beauty sleep, you need to hibernate.",
  "People like you don't grow on trees. They swing from them.",
  "I sure hope there's a lifeguard in your gene pool.",
  "Go ahead and tell me everything you know. I've got a spare ten seconds.",
  "Every time I think of all the people that haven't met you, I get jealous.",
  "You're so far up your own ass you can lick your tonsils.",
  "Some people bring joy wherever they go. You bring joy whenever you go.",
  "You've got a face that could turn fresh milk sour.",
  "Stop thinking everyone's your equal. That's offensive to a lot of people.",
  "A lot of people live and learn. You just live.",
  "You remind me of myself. Back when I was young and stupid.",
  "You've got a face like a bag of elbows.",
  "I don't want you to turn the other cheek - it's just as ugly.",
  "What drugs are you on, stupid pills?",
  "Let's go to the zoo. I've always wanted to meet your family.",
  "A half-wit gave you a piece of his mind, and you held on to it.",
  "Last time I saw something like you, I flushed it.",
  "It's too bad stupidity isn't painful.",
  "You're as strong as an ox. Just not as intelligent.",
  "Come again when you can't stay as long.",
  "People like you are the reason God doesn't talk to us anymore.",
  "You're kind of like Rapunzel but instead of letting your hair down, you let everyone down in your life."
}
