-- * _JOKER_VERSION: 0.0.1 ** Please do not modify this line.
--[[----------------------------------------------------------
	Joker - Jokes, Riddles, Fun Facts, & Other Tomfoolery
  ----------------------------------------------------------
  *
  * ADDING YOUR OWN JOKES:
  * Be aware that modifying this file incorrectly could break Joker,
  * so for normal users I recommend just compiling your jokes in the
  * '_MyCustomJokes.lua' file instead.
  *
  * COMPILATION: ESO-related jokes
	*
	* SOURCES:
  * Reddit Search, 
  * Google Search
	*
]]--

JokerData = JokerData or {}
JokerData.Config = JokerData.Config or {}

JokerData.Config.Cat = {
  label = "Cat Facts",
  command = "cat",
  joke = true,
  nsfw = false,
  whitelistSlashCommand = true
}

JokerData.Cat = {
  "In relation to their body size, cats have the largest eyes of any mammal.",
  "When well treated, a cat can live twenty or more years but the average life span of a domestic cat is 14 years.",
  "There are cats who have survived falls from over 32 stories (320 meters) onto concrete.",
  "The chlorine in fresh tap water irritates sensitive parts of the cat's nose. Let tap water sit for 24 hours before giving it to a cat.",
  "Cats eat grass to aid their digestion and to help them get rid of any fur in their stomachs.",
  "The way you treat kittens in the early stages of it's life will render it's personality traits later in life.",
  "Cats can jump up to 7 times their tail length.",
  "A Chinese cat named Baidianr (meaning 'white spot') had a unique ability to choose World Cup winners. He predicted the winner of the soccer competition 6 years in a row, before he died on June 2, 2018, just before the event ended.",
  "Blue-eyed, pure white cats are frequently deaf.",
  "Some notable people who disliked cats:  Napoleon Bonaparte, Dwight D. Eisenhower, Hitler, Dylan Orrell.",
  "A tiger's stripes are like fingerprints; no two animals have the same pattern.",
  "For a cat at rest, the average heart rate usually is between 150 and 180 bpm, more than twice that of a human, which averages 70 bpm.",
  "A steady diet of dog food may cause blindness in your cat - it lacks taurine.",
  "Every year, nearly four million cats are eaten in China as a delicacy.",
  "Unlike humans, cats do not need to blink their eyes on a regular basis to keep their eyes lubricated.",
  "The Bengal is the result of crossbreeding between domestic cats and Asian leopard cats, and its name is derived from the scientific name for the Asian leopard cat (Felis bengalensis).",
  "Jaguars are the only big cats that don't roar.",
  "Cat owners are 17% more likely to have a graduate degree than non cat owners.",
  "Lions are the only cats that live in groups, called prides. Every female within the pride is usually related.",
  "Six-toed kittens are so common in Boston and surrounding areas of Massachusetts that experts consider it an established mutation.",
  "Cat's cannot see in total darkness, however their vision is much better than a human's in semidarkness because their retinas are much more sensitive to light.",
  "A cat's normal pulse is 140-240 beats per minute, with an average of 195.",
  "BIG.",
  "Cats can survive falls from up to 65 feet or more.",
  "Florence Nightingale owned more than 60 cats in her lifetime.",
  "It may take as long as 2 weeks for a kitten to be able to hear well.  Their eyes usually open between 7 and 10 days, but sometimes it happens in as little as 2 days.",
  "A queen (female cat) can begin mating when she is between 5 and 9 months old.",
  "If a cat is frightened, put your hand over its eyes and forehead, or let him bury his head in your armpit to help calm him.",
  "Cats and humans have nearly identical sections of the brain that control emotion.",
  "Cats have scent glands along their tail, their forehead, lips, chin, and the underside of their front paws.",
  "rerewr",
  "Basically all cartoon cats lied to us: Raw fish is off the table for cats as well.",
  "While Chartreux cats aren't very vocal, they are sociable and communicate through eye contact and body language.",
  "Cat's urine glows under a black light.",
  "Hello.",
  "When a cats rubs up against you, the cat is marking you with it's scent claiming ownership.",
  "The strongest climber among the big cats, a leopard can carry prey twice its weight up a tree.",
  "Tylenol and chocolate are both poisionous to cats.",
  "Among many other diseases, cats can suffer from anorexia, senility, feline AIDS and acne.",
  "A cat's normal temperature varies around 101 degrees Fahrenheit.",
  "The Amur leopard is one of the most endangered animals in the world.",
  "Ever wondered why kittens can all be different colours and look so different from their mums? The fact is that one in four pregnant cats carries kittens fathered by more than one mate. A fertile female may mate with several tom-cats, which fertilise different eggs each time.",
  "Cats have individual preferences for scratching surfaces and angles. Some are horizontal scratchers while others exercise their claws vertically.",
  "A cat can’t climb head first down a tree because every claw on a cat’s paw points the same way. To get down from a tree, a cat must back down.",
  "Cats only sweat through their foot pads.",
  "Exposure to UV light with hairless or partially-hairless cats can result in sunburn, even during cloudy or shady conditions. If your cat risks overexposure, consider applying sunscreen daily.",
  "A sexually-active feral tom-cat 'owns' an area of about three square miles and 'sprays' to mark his territory with strong smelling urine.",
  "Cats are subject to gum disease and to dental caries. They should have their teeth cleaned by the vet or the cat dentist once a year.",
  "Cats take between 20-40 breaths per minute.",
  "If your cat snores, or rolls over on his back to expose his belly, it means he trusts you.",
  "Cats have 32 muscles that control the outer ear (compared to human's 6 muscles each). A cat can rotate its ears independently 180 degrees, and can turn in the direction of sound 10 times faster than those of the best watchdog.",
  "Mark Twain was undeniably an ailurophile. He had up to 19 cats at one time and gave them such memorable names as Beelzebub, Buffalo Bill, and Soapy Sal.",
  "In an average year, cat owners in the United States spend over $2 billion on cat food.",
  "The claws on the cat’s back paws aren’t as sharp as the claws on the front paws because the claws in the back don’t retract and, consequently, become worn.",
  "Cats have a third eyelid called a 'haw'. It’s generally only visible when they’re unwell.",
  "Long hair.",
  "Despite its traditionally wild roots, the Bengal is domestic and will gladly make itself in the indoor 'jungle' of your home.",
  "There are approximately 60,000 hairs per square inch on the back of a cat and about 120,000 per square inch on its underside.",
  "Miacis, the primitive ancestor of cats, was a small, tree-living creature of the late Eocene period, some 45 to 50 million years ago.",
  "Cats can distinguish different flavors in water.",
  "The female cat reaches sexual maturity within 6 to 10 months; most veterinarians suggest spaying the female at 5 months, before her first heat period. The male cat usually reaches sexual maturity between 9 and 12 months.",
  "AS.",
  "About 37% of American homes today have at least 1 cat.",
  "Cat families usually play best in even numbers. Cats and kittens should be acquired in pairs whenever possible.",
  "When kittens ages to weeks five and six, they should start making the transition to dry food.",
  "Among domestic cats, males are more likely to fight than females.",
  "The average cat food meal is the equivalent to about five mice.",
  "A domestic cat can run at speeds of 30 mph.",
  "Almost 10% of a cat's bones are in its tail, and the tail is used to maintain balance.",
  "Cats come back to full alertness from the sleep state faster than any other creature.",
  "Approximately 40% of cats have a dominant paw. The rest are ambidextrous.",
  "The Indiana State Prison allows prisoners to adopt a cat and keep it in their cell. They are meant to improve the mood of the prisoners.",
  "Cats sleep 70% of their lives.",
  "Cats step with both left legs, then both right legs when they walk or run.",
  "Kittens who are taken along on short, trouble-free car trips to town tend to make good passengers when they get older. They get used to the sounds and motions of traveling and make less connection between the car and the visits to the vet.",
  "Small.",
  "A cat can spend five or more hours a day grooming himself.",
  "Cats have fur",
  "The more cats are spoken to, the more they will speak back. You will learn a lot from your cat's wide vocabulary of chirps and meows.",
  "Cats purr at the same frequency as an idling diesel engine, about 26 cycles per second.",
  "Phoenician cargo ships are thought to have brought the first domesticated cats to Europe in about 900 BC.",
  "Black cats are less likely to be adopted because of their 'appearance'.",
  "Cats are the most popular pet in the United States: There are 88 million pet cats and 74 million dogs.",
  "Original kitty litter was made out of sand but it was replaced by more absorbent clay in 1948.",
  "The cat skull is unusual among mammals in having very large eye sockets and a powerful and specialized jaw.",
  "The Ancient Egyptian word for cat was mau, which means 'to see'.",
  "Polydactyl cats are also referred to as 'Hemingway cats' because the author was so fond of them.",
  "The life expectancy of cats has nearly doubled over the last fifty years.",
  "The smallest breed of domestic cat is the Singapura or 'Drain Cat' of Singapore. Adult females weigh in at an average of 4lbs.",
  "Cats and kittens should be acquired in pairs whenever possible as cat families interact best in pairs.",
  "In 1879, Belgium unsuccessfully tried to use cats to deliver mail.",
  "Declawing a cat is the same as cutting a human's fingers off at the knuckle. There are several alternatives to a complete declawing, including trimming or a less radical (though more involved) surgery to remove the claws. Instead, train your cat to use a scratching post.",
  "Hearing is the strongest of cat's senses: They can hear sounds as high as 64 kHz — compared with humans, who can hear only as high as 20 kHz.",
  "One legend claims that cats were created when a lion on Noah's Ark sneezed and two kittens came out.",
  "The Sphynx was originally known as the Canadian Hairless Cat. The breed originated in Toronto, and was renamed to Sphynx, a nod to the famous limestone sculpture in the Egyptian Desert.",
  "The female cat reaches sexual maturity at around 6 to 10 months and the male cat between 9 and 12 months.",
  "A cat can jump 5 times as high as it is tall.",
  "Koko the gorilla got a pet cat for her birthday in 1985 after she requested to have one as a birthday present.",
  "Cats should not be fed tuna exclusively, as it lacks taurine, an essential nutrient required for good feline health.  Make sure you have the proper Pet supplies to keep your cat happy and healthy.",
  "Abraham Lincoln, being the ailurophile that he was, once rescued three stray kittens and ensured that they were fed and found homes.",
  "The leopard is the most widespread of all big cats.",
  "A cat will spend nearly 30% of her life grooming herself.",
  "Cats respond better to women than to men, probably due to the fact that women's voices have a higher pitch.",
  "A house cat is faster than Usain Bolt.",
  "In multi-cat households, cats of the opposite sex usually get along better.",
  "A cat that bites you for rubbing his stomach is often biting from pleasure, not anger.",
  "In households in the UK and USA, there are more cats kept as pets than dogs. At least 35% of households with cats have 2 or more cats.",
  "A cat's brain is 90% similar to a human's — more similar than to a dog's.",
  "A group of cats is called a clowder.",
  "Cats lived with soldiers in trenches, where they killed mice during World War I.",
  "A cat can die from essential oils",
  "People who are allergic to cats are actually allergic to cat saliva or to cat dander. If the resident cat is bathed regularly the allergic people tolerate it better.",
  "Hi.",
  "Many people think that the Turkish Van is simply a color variation of the Turkish Angora, but in fact, they are distinct breeds that developed in different parts of Turkey.",
  "Recent studies have shown that cats can see blue and green. There is disagreement as to whether they can see red.",
  "An adult lion's roar can be heard up to five miles (eight kilometers) away.",
  "A cat has two vocal chords, and can make over 100 sounds.",
  "Russian scientists discovered in the 1930s that Siamese kittens kept in very warm rooms didn't develop the breed's signature dark patches.",
  "In Siam, the cat was so revered that one rode in a chariot at the head of a parade celebrating the new king.",
  "Mature cats with no health problems are in deep sleep 15 percent of their lives. They are in light sleep 50 percent of the time. That leaves just 35 percent awake time, or roughly 6-8 hours a day.",
  "A cat has more bones than a human being; humans have 206 and the cat has 230 bones.",
  "Baking chocolate is the most dangerous chocolate to your cat.",
  "Some common houseplants poisonous to cats include: English Ivy, iris, mistletoe, philodendron, and yew.",
  "Cats love playing with yarn, ribbons, and fishing-rode style toys. However, cats should not be left alone with anything that they could get tangled in.",
  "Cats were mythic symbols of divinity in ancient Egypt.",
  "When cats grimace, they are usually 'taste-scenting.' They have an extra organ that, with some breathing control, allows the cats to taste-sense the air.",
  "Cats use their whiskers to detect if they can fit through a space.",
  "The cat has 500 skeletal muscles (humans have 650).",
  "The average lifespan of an outdoor-only (feral and non-feral) is about 3 years; an indoor-only cat can live 16 years and longer. Some cats have been documented to have a longevity of 34 years.",
  "Heat occurs several times a year and can last anywhere from 3 to 15 days.",
  "Domestic cats spend about 70 percent of the day sleeping. And 15 percent of the day grooming.",
  "A form of AIDS exists in cats.",
  "Cat families usually play best in even numbers. Cats and kittens should be aquired in pairs whenever possible.",
  "Today there are about 100 distinct breeds of the domestic cat.",
  "The first formal cat show was held in England in 1871; in America, in 1895.",
  "Cats dislike citrus scent.",
  "The CIA spent US$20 million in the 60s training cats to spy on the Soviets. The first spy cat was hit by a taxi.",
  "Blue-eyed, white cats are often prone to deafness.",
  "Most cats are lactose intolerant, and milk can cause painful stomach cramps and diarrhea. It's best to forego the milk and just give your cat the standard: clean, cool drinking water.",
  "In the original Italian version of Cinderella, the benevolent fairy godmother figure was a cat.",
  "On average, a cat will sleep for 16 hours a day.",
  "All cats have three sets of long hairs that are sensitive to pressure - whiskers, eyebrows,and the hairs between their paw pads.",
  "Legend holds that the Chartreux once lived alongside the Carthusian monks of France.",
  "Kittens start to dream when they’re about a week old.",
  "The ancient Egyptians were the first to tame the cat (in about 3000 BC), and used them to control pests.",
  "The Maine Coon cat is America's only natural breed of domestic feline. It is 4 to 5 times larger than the Singapura, the smallest breed of cat.",
  "Cats don't go through menopause, so they can continue to breed into their senior years.",
  "By the time a cat is 9 years old, it will only have been awake for three years of its life.",
  "Your cat's instincts tell her that a paperweight or knickknack could turn out to be a mouse. Her poking paw would send it scurrying, giving her a good game. This is probably why cats always seem to be knocking the glasses off your counter tops!",
  "Neutering a male cat will, in almost all cases, stop him from spraying (territorial marking), fighting with other males (at least over females), as well as lengthen his life and improve its quality.",
  "The technical term for 'hairball' is 'bezoar.'",
  "In one stride, a cheetah can cover 23 to 26 feet (7 to 8 meters).",
  "In the Middle Ages, during the Festival of Saint John, cats were burned alive in town squares.",
  "A cat's kidneys are so efficient, it can survive on a diet consisting only of meat, with no additional water, and can even rehydrate by drinking seawater.",
  "Most cats adore sardines.",
  "A tomcat (male cat) can begin mating when he is between 7 and 10 months old.",
  "Long, muscular hind legs enable snow leopards to leap seven times their own body length in a single bound.",
  "Cats use their whiskers to judge whether they’ll fit through a space.",
  "Not every cat gets 'high' from catnip. Whether or not a cat responds to it depends upon a recessive gene: no gene, no joy.",
  "Cats born with 6 or 7 front toes and extra back toes are called polydactl.",
  "A cat's cerebral cortex (the part of the brain in charge of cognitive information processing) has 300 million neurons, compared with a dog's 160 million.",
  "Mother cats teach their kittens to use the litter box.",
  "A happy cat holds her tail high and steady.",
  "At night, Disneyland is overrun by cats. The theme park feeds them and takes care of them though, because they keep the rodent population in check.",
  "If a cat is frightened, the hair stands up fairly evenly all over the body; when the cat is threatened or is ready to attack, the hair stands up only in a narrow band along the spine and tail.",
  "Lil' Bunny Sue Roux is a cat who was born with no front legs, and walks upright like a kangaroo. https://www.instagram.com/lilbunnysueroux",
  "Cats have free-floating clavicle bones that attach their shoulders to their forelimbs, which allows them to squeeze through very small spaces.",
  "Cats can hear the ultrasonic noises that rodents and dolphins make to communicate.",
  "My cat is fat...",
  "When cats bring dead animals back to their humans, they are 'teaching them to hunt' as they would with a younger cat.",
  "A cat cannot see directly under its nose.",
  "Cats have been domesticated for half as long as dogs have been.",
  "When a domestic cat goes after mice, about 1 pounce in 3 results in a catch.",
  "Many cats cannot properly digest cow's milk. Milk and milk products give them diarrhea.",
  "It is working fine now.",
  "Cats with long, lean bodies are more likely to be outgoing, and more protective and vocal than those with a stocky build.",
  "In most US states, declawing cats is legal but in the European Union it is not.",
  "The ancient Egyptians were the first civilisation to realise the cat's potential as a vermin hunter and tamed cats to protect the corn supplies on which their lives depended.",
  "Like humans, cats tend to favor one paw over another.",
  "Colonel Meow, a Himalayan-Persian mix who became famous on social media websites for his extremely long fur and scowling face, holds the Guinness world record for longest hair on a cat (nine inches).",
  "Cats' hearing is much more sensitive than humans and dogs.",
  "Cats can be prone to fleas in the summertime: 794 fleas were counted on one cat by a Cats Protection volunteer in the summer of 1992.",
  "It has been scientifically proven that stroking a cat can lower one's blood pressure.",
  "A female cat will be pregnant for approximately 9 weeks - between 62 and 65 days from conception to delivery.",
  "A cat can sprint at about thirty-one miles per hour.",
  "When asked if her husband had any hobbies, Mary Todd Lincoln is said to have replied 'cats.'",
  "The french tuxedo kitty, Félix, aka 'Astrocat', was the first cat to go to space. She survived the trip.",
  "Neutering a cat extends its life span by two or three years.",
  "Most breeds of cat have a noted fondness for settling in high places, or perching. In the wild, a higher place may serve as a concealed site from which to hunt.",
  "Cats can judge within 3 inches the precise location of a sound being made 1 yard away.",
  "Cats make more than 100 different sounds whereas dogs make around 10.",
  "I don't know anything about cats.",
  "Cats bury their feces to cover their trails from predators.",
  "The special sensory organ called the Jacobson's organ allows a cat to have 14 times the sense of smell of a human. It consists of two fluid-filled sacs that connect to the cat's nasal cavity and is located on the roof of their mouth behind their teeth.",
  "The Maine Coone is the only native American long haired breed.",
  "The little tufts of hair in a cat’s ear that help keep out dirt direct sounds into the ear, and insulate the ears are called 'ear furnishings.'",
  "Tests done by the Behavioral Department of the Musuem of Natural History conclude that while a dog's memory lasts about 5 minutes, a cat's recall can last as long as 16 hours.",
  "The cat appears to be the only domestic companion animal not mentioned in the Bible.",
  "A cat has a total of 24 whiskers, 4 rows of whiskers on each side. The upper two rows can move independently of the bottom two rows.",
  "A cat sees about 6 times better than a human at night, and needs 1/6 the amount of of light that a human does - it has a layer of extra reflecting cells which absorb light.",
  "Cats, especially older cats, do get cancer. Many times this disease can be treated successfully.",
  "The gene that codes orange fur is on the X chromosome, so female cats must inherit two orange genes to end up with orange fur, while male cats only need one.",
  "Ancient Egyptian family members shaved their eyebrows in mourning when the family cat died.",
  "Female felines are 'superfecund,' which means that each of the kittens in her litter can have a different father.",
  "The domestic cat is the only species able to hold its tail vertically while walking. You can also learn about your cat's present state of mind by observing the posture of his tail.",
  "Cat owners are 25% likely to pick George Harrison as their favorite Beatle.",
  "Your cat recognizes your voice but just acts too cool to care (probably because they are).",
  "The Egyptian Mau’s name is derived from the Middle Egyptian word mjw, which means cat. But contrary to its name, it’s unclear whether the modern Egyptian Mau actually originated in Egypt.",
  "Siamese kittens are born white because of the heat inside the mother's uterus before birth. This heat keeps the kittens' hair from darkening on the points.",
  "Cats respond most readily to names that end in an 'ee' sound.",
  "Normal body temperature for a cat is 102 degrees Fahrenheit.",
  "123123.",
  "Purring does not always indicate that a cat is happy. Cats will also purr loudly when they are distressed or in pain.",
  "Both humans and cats have identical regions in the brain responsible for emotion.",
  "Unlike kittens, adult cats don’t release any particular key hormones during sleep. They snooze all day just because they can. :)",
  "The first official cat show in the UK was organised at Crystal Palace in 1871.",
  "A cat's appetite is the barometer of its health. Any cat that does not eat or drink for more than two days should be taken to a vet.",
  "On September 6,1950, a four-month-old kitten belonging to Josephine Aufdenblatten of Geneva, Switzerland followed a group of climbers to the top of the 14,691 -ft. Matterhorn in the Alps.",
  "Approximately 40,000 people are bitten by cats in the U.S. annually.",
  "The silks created by weavers in Baghdad were inspired by the beautiful and varied colors and markings of cat coats. These fabrics were called 'tabby' by European traders.",
  "After humans, mountain lions have the largest range of any mammal in the Western Hemisphere.",
  "Cats lose almost as much fluid in the saliva while grooming themselves as they do through urination.",
  "Since cats are so good at hiding illness, even a single instance of a symptom should be taken very seriously.",
  "Cats can have three litters a year, or approximately 12 kittens.",
  "Cats have 30 vertebrae--5 more than humans have.",
  "Of all the species of cats, the domestic cat is the only species able to hold its tail vertically while walking. All species of wild cats hold their tail horizontally or tucked between their legs while walking.",
  "The frequency of a domestic cat's purr is the same at which muscles and bones repair themselves.",
  "It has been scientifically proven that owning cats is good for our health and can decrease the occurrence of high blood pressure and other illnesses.",
  "A cat's tongue has tiny barbs on it.",
  "The Chartreux is distinguished by a woolly blue-grey coat, a robust body poised over small paws, and full cheeks with a mouth that always appear to be smiling.",
  "A female cat is called a 'molly' or a 'queen'.",
  "Ext.",
  "The cat's footpads absorb the shocks of the landing when the cat jumps.",
  "A cat's hearing is much more sensitive than humans and dogs.",
  "It was illegal to slay cats in ancient Egypt, in large part because they provided the great service of controlling the rat population.",
  "A cat’s nose pad is ridged with a unique pattern, just like the fingerprint of a human.",
  "Cats lack antibodies against dog blood so they can only receive it via a transfusion once. The second time would kill them.",
  "The goddess of love, beauty, and fertility in Norse mythology, Freyja was the first cat lady. She is depicted in stories as riding a chariot that was drawn by cats.",
  "Kittens sleep so much because the growth hormone is only released when they sleep.",
  "A cat uses its whiskers for measuring distances.  The whiskers of a cat are capable of registering very small changes in air pressure.",
  "The Manx hails from the Isle of Man in the Irish Sea, and many Manx are tailless, a condition believed to have been caused by a dominant genetic mutation that spread among the island's cat population.",
  "The name 'jaguar' comes from a Native American word meaning 'he who kills with one leap'.",
  "Bla.",
  "Evidence suggests domesticated cats have been around since 3600 B.C., 2,000 years before Egypt's pharaohs.",
  "Tigers are excellent swimmers and do not avoid water.",
  "Stroking a cat can help to relieve stress, and the feel of a purring cat on your lap conveys a strong sense of security and comfort.",
  "The softest part of a cat is most definitely its cheek area.",
  "A cat's purr may be a form of self-healing, as it can be a sign of nervousness as well as contentment.",
  "If they have ample water, cats can tolerate temperatures up to 133 °F.",
  "Cats love to eat olives or for that matter anything preserved in brine.",
  "The most popular pedigreed cat in North America is the Persian cat, followed by the Main Coon and the Siamese cat.",
  "Julius Ceasar, Henri II, Charles XI, and Napoleon were all afraid of cats.",
  "A cat named Dusty, aged 1 7, living in Bonham, Texas, USA, gave birth to her 420th kitten on June 23, 1952.",
  "Black cats are bad luck in the United States, but they are good luck in the United Kingdom and Australia.",
  "Cats sleep 16 to 18 hours per day. When cats are asleep, they are still alert to incoming stimuli. If you poke the tail of a sleeping cat, it will respond accordingly.",
  "The cheetah is the world's fastest land mammal. It can run at speeds of up to 70 miles an hour (113 kilometers an hour).",
  "Here is a video of some cats in zero gravity. youtu.be/O9XtK6R1QAk",
  "The ability of a cat to reflexively twist its body and balance itself during a fall is known as the 'cat righting reflex'.",
  "In ancient Egypt, killing a cat was a crime punishable by death.",
  "Domestic cats purr both when inhaling and when exhaling.",
  "Cats have the largest eyes of any mammal.",
  "It is estimated that cats can make over 60 different sounds.",
  "Thank to an extremely efficient pair of kidneys, cats can hydrate themselves by drinking salt water.",
  "All Scottish Folds descended from Susie, a white barn cat discovered in Scotland in the early 1960s. Susie sported the breed's folded ears – the result of a genetic mutation – and passed on the trait through breeding.",
  "Cats' hearing stops at 65 khz (kilohertz); humans' hearing stops at 20 khz.",
  "Wikipedia has a recording of a cat meowing, because why not?",
  "Cats have been domesticated for around 4,000 years. While they were once valued for their hunting abilities, they are now valued for their companionship and loving behavior.",
  "A cat will tremble or shiver when it is in extreme pain.",
  "Cats have about 130,000 hairs per square inch (20,155 hairs per square centimeter).",
  "There is a species of cat smaller than the average housecat. It is native to Africa and it is the Black-footed cat (Felis nigripes). Its top weight is 5.5 pounds.",
  "The first true cats came into existence about 12 million years ago and were the Proailurus.",
  "My cat is 18 pounds.",
  "Cats can't taste sweetness.",
  "Cats have a layer called the tapetum lucidum just behind their retina which reflects light inside the eye, helping it capture more light. This reflected light is the glow you see when taking a photo of a cat with the flash on.",
  "The average lifespan of an outdoor-only cat is about 3 to 5 years while an indoor-only cat can live 16 years or much longer.",
  "Tigers have been hunted for their skin, bones, and other body parts, used in traditional Chinese medicine.",
  "A domestic cat can sprint at about 31 miles per hour.",
  "A tortoiseshell is black with red or orange markings and a calico is white with patches of red, orange and black.",
  "Loyal, playful, and alert, Manx are considered to be more 'doglike' than other cats.",
  "Cat.",
  "Cats see six times better in the dark and at night than humans.",
  "The average litter of kittens is between 2 - 6 kittens.",
  "Female cats are typically right-pawed while male cats are typically left-pawed.",
  "Cats have 30 vertebrae (humans have 33 vertebrae during early development; 26 after the sacral and coccygeal regions fuse)",
  "In the 15th century, Pope Innocent VIII began ordering the killing of cats, pronouncing them demonic.",
  "When cats leave their poop uncovered, it is a sign of aggression to let you know they don't fear you.",
  "There are only two escalators in the state of Wyoming.",
  "A cat's field of vision is about 200 degrees.",
  "Cats have 30 teeth (12 incisors, 10 premolars, 4 canines, and 4 molars), while dogs have 42. Kittens have baby teeth, which are replaced by permanent teeth around the age of 7 months.",
  "Cats lap liquid from the underside of their tongue, not from the top.",
  "Compared to other felines, domestic cats have narrowly spaced canine teeth, adapted to their preferred prey of small rodents.",
  "Cats can get tapeworms from eating mice. If your cat catches a mouse it is best to take the prize away from it.",
  "According to a Gallup poll, most American pet owners obtain their cats by adopting strays.",
  "Abraham Lincoln loved cats. He kept four of them while he lived in the White House.",
  "The mountain lion and the cheetah share an ancestor.",
  "A cat’s spine can rotate more than the spines of most other animals, and their vertebrae have a special, flexible, elastic cushioning on the disks, which gives it even more flexibility.",
  "Esta durmiendo.",
  "People who own cats have on average 2.1 pets per household, where dog owners have about 1.6.",
  "A cat was mayor of Talkeetna, Alaska, for 20 years. His name is Stubbs, and he died on July 23, 2017.",
  "When a cat yawns, it's mouth opens so wide that you can count every tooth.",
  "Tomcats can mate at anytime, while quenns can only mate during a period of time called heat or estrus.",
  "In the 1960s, the CIA tried to turn a cat into a bonafide spy by implanting a microphone into her ear and a radio transmitter at the base of her skull. She somehow survived the surgery but got hit by a taxi on her first mission.",
  "Cat fanciers bred and exhibited Maus in Europe until World War II, when attention toward the cat waned and it nearly went extinct.",
  "The fear of cats is called 'Ailurophobia'",
  "Cats do not think that they are little people. They think that we are big cats. This influences their behavior in many ways.",
  "All cats need taurine in their diet to avoid blindness. Cats must also have fat in their diet as they are unable to produce it on their own.",
  "Cat bites are more likely to become infected than dog bites.",
  "The collective noun for kittens is a 'kindle'.",
  "The technical term for a cat’s hairball is a bezoar.",
  "A cat has more bones than a human; humans have 206, and the cat - 230.",
  "Exposing cats and dogs to marijuana can help reduce the suffering from a chronic and painful illness.",
  "A cat will tremble or shiver when it is extreme pain.",
  "You check your cats pulse on the inside of the back thigh, where the leg joins to the body. Normal for cats: 110-170 beats per minute.",
  "A cat's whiskers are thought to be a kind of radar, which helps a cat gauge the space it intends to walk through.",
  "The cat who holds the record for the longest non-fatal fall is Andy. He fell from the 16th floor of an apartment building (about 200 ft/.06 km) and survived.",
  "In Islam, cats are revered for their cleanliness. Muhammad is reported to have said that 'a love of cats is an aspect of faith'.",
  "Cat litter was 'invented' in 1947 when Edward Lowe asked his neighbor to try a dried, granulated clay used to sop up grease spills in factories. (In 1990, Mr. Lowe sold his business for $200 million.)",
  "British cat owners spend roughly 550 million pounds yearly on cat food.",
  "A cat's brain is more similar to a man's brain than that of a dog.",
  "In 1987, cats overtook dogs as the number one pet in America (about 50 million cats resided in 24 million homes in 1986). About 37% of American homes today have at least one cat.",
  "Like birds, cats have a homing ability that uses its biological clock, the angle of the sun, and the Earth's magnetic field. A cat taken far from its home can return to it. But if a cat's owners move far from its home, the cat can't find them.",
  "Gharib.",
  "Cheetahs do not roar, as the other big cats do. Instead, they purr.",
  "The life expectancy of cats has nearly doubled since 1930 - from 8 to 16 years.",
  "Approximately 80% of orange tabbies are male.",
  "Most cats don't like water because their coats do not insulate them well enough.",
  "A cat has five toes on his front paws, and four on the back, unless he's a polydactyl.",
  "Unlike other cats, lions have a tuft of hair at the end of their tails.",
  "When your cats rubs up against you, she is actually marking you as 'hers' with her scent. If your cat pushes his face against your head, it is a sign of acceptance and affection.",
  "Oftentimes shelters won't let black cats be adopted around Halloween out of a fear that they may be sacrificed.",
  "When cats run, their backs contract and extend to give them maximum stride. Their shoulder blades are not attached with bone, but with muscle, and this gives a cat even greater extension and speed.",
  "A male cat is called a tom.",
  "In 1987 cats overtook dogs as the number one pet in America.",
  "Cats that live together sometimes rub each others heads to show that they have no intention of fighting. Young cats do this more often, especially when they are excited.",
  "The ancestor of all domestic cats is the African Wild Cat which still exists today.",
  "Never give your cat aspirin unless specifically prescribed by your veterinarian; it can be fatal. Never ever give Tylenol to a cat.  And be sure to keep anti-freeze away from all animals - it's sweet and enticing, but deadly poison.",
  "Cats can move their ears 180 degrees.",
  "At 4 weeks, it is important to play with kittens so that they do not develope a fear of people.",
  "A cat's jaw has only up and down motion; it does not have any lateral, side to side motion, like dogs and humans.",
  "Kangaroos can't hop backwards",
  "A cat has approximately 60 to 80 million olfactory cells (a human has between 5 and 20 million).",
  "Cats can't taste sweets.",
  "Angora.",
  "Besides smelling with their nose, cats can smell with an additional organ called the Jacobson's organ, located in the upper surface of the mouth.",
  "F.",
  "The lightest cat on record is a blue point Himalayan called Tinker Toy, who weighed 1 pound, 6 ounces (616 g). Tinker Toy was 2.75 inches (7 cm) tall and 7.5 inches (19 cm) long.",
  "A female Amur leopard gives birth to one to four cubs in each litter.",
  "If your cat snores or rolls over on his back to expose his belly, it means he trusts you.",
  "Fossil records from two million years ago show evidence of jaguars.",
  "The place where Julius Caesar was murdered is now a cat sanctuary.",
  "The average female housecat could give birth to ove 100 kittens in her lifetime.",
  "A healthy cat has a temperature between 38 and 39 degrees Celcius.",
  "Some Siamese cats appear cross-eyed because the nerves from the left side of the brain go to mostly the right eye and the nerves from the right side of the brain go mostly to the left eye. This causes some double vision, which the cat tries to correct by 'crossing' its eyes.",
  "The cat's tail is used to maintain balance.",
  "The Pilgrims were the first to introduce cats to North America.",
  "Only 11.5% of people consider themselves 'cat people'.",
  "Many Egyptians worshipped the goddess Bast, who had a woman’s body and a cat’s head.",
  "Cats can be taught to walk on a leash, but a lot of time and patience is required to teach them. The younger the cat is, the easier it will be for them to learn.",
  "Mountain lions are strong jumpers, thanks to muscular hind legs that are longer than their front legs.",
  "When a cat drinks, its tongue - which has tiny barbs on it - scoops the liquid up backwards.",
  "The world's largest cat measured 48.5 inches long.",
  "The largest breed of cat is the Ragdoll with males weighing in at 1 5 to 20 lbs. The heaviest domestic cat on record was a neutered male tabby named Himmy from Queensland, Australia who weighed 46 lbs. 1 5 oz.",
  "The cheetah is the only cat that doesn't have retractable claws.",
  "The first cat show was in 1871 at the Crystal Palace in London.",
  "On February 28, 1 980 a female cat climbed 70 feet up the sheer pebble-dash outside wall of a block of flats in Bradford, Yorkshire and took refuge in the roof space. She had been frightened by a dog.",
  "A cats whiskers are the exact width of their body.",
  "If you really want to treat your cat, get some lactose-free milk at the grocery store and offer some to the kitty.",
  "Cats like being brushed by their owners, because it reminds them of their mother.",
  "Cats are now Britain's favourite pet: there are 7.7 million cats as opposed to 6.6 million dogs.",
  "Not every cat gets 'high' from catnip. If the cat doesn't have a specific gene, it won't react (about 20% do not have the gene). Catnip is non-addictive.",
  "The Maine Coon is 4 to 5 times larger than the Singapura, the smallest breed of cat.",
  "Cucumbers look enough like a snake to cause a cat's instinctive fear of snakes to kick in, causing it to panic and flee.",
  "Ninety-two per cent of cats are 'Moggies', or, non-pedigrees. How did the name 'Moggie' come about? One theory holds that it comes from old English dialect, where 'Moggie' was used to designate a loose woman or prostitute. It is thought that this name was given to cats because they mate repeatedly with different males when they are in season.",
  "Towser 'The Mouser' of Glenturret Distillery in Crieff, Scotland, holds the Guinness World Record for the most mice caught (28,899).",
  "A kitten will typically weigh about 3 ounces at birth.  The typical male housecat will weigh between  7 and 9 pounds, slightly less for female housecats.",
  "Approximately 1/3 of cat owners think their pets are able to read their minds.",
  "'Cat people' are 11% more likely to be introverted than others.",
  "Owning a cat can reduce the risk of heart attacks and strokes by more than a third, researchers found.",
  "Due to the controversy, though loved by most, the Kashmir is overlooked by many cat fanciers.",
  "Cats aren’t the only animals that purr — squirrels, lemurs, elephants, and even gorillas purr too.",
  "In ancient Egypt, mummies were made of cats, and embalmed mice were placed with them in their tombs. In one ancient city, over 300,000 cat mummies were found.",
  "A cats field of vision is about 185 degrees.",
  "The oldest cat video on YouTube dates back to 1894.",
  "Tabby cats are thought to get their name from Attab, a district in Baghdad, now the capital of Iraq.",
  "The color of the points in Siamese cats is heat related. Cool areas are darker.",
  "Cats have a longer-term memory than dogs, especially when they learn by actually doing rather than simply seeing.",
  "Issac Newton decided to invent the cat flap because his own cat, Spithead, kept opening the door and spoiling his light experiments.",
  "The oldest cat on record was probably 'Puss', a tabby owned by Mrs. Holway of Clayhidon, Devon. Having celebrated his 36th birthday on November 28, 1939, Puss died the following day.",
  "In the wild, lions live for an average of 12 years and up to 16 years. They live up to 25 years in captivity.",
  "Many cats love having their forehead gently stroked.",
  "It has been estimated that a cat yawns on the average of 109,500 times in his life.",
  "The domestic cat (Felis catus) is a small, typically furry, carnivorous mammal.",
  "As child Nikola Tesla was inspired to understand the secrets of electricity after being shocked by static electricity from his beloved cat, Macak.",
  "Cats can predict earthquakes. We humans are not 100% sure how they do it. There are several different theories.",
  "In just 7 years, one un-spayed female cat and one un-neutered male cat and their offspring can result in 420,000 kittens.",
  "A female cat will be pregnant for approximately 9 weeks or between 62 and 65 days from conception to delivery.",
  "America’s cats, including housecats that adventure outdoors and feral cats, kill between 1.3 billion and 4.0 billion birds in a year.",
  "Edward Lear, author of 'The Owl and the Pussycat', is said to have had his new house in San Remo built to exactly the same specification as his previous residence, so that his much-loved tabby, Foss, would immediately feel at home.",
  "Cats have 38 chromosomes in each zygote cell.",
  "Blackie became the richest cat in history when he inherited 15 million British Pounds.",
  "Leonardo da Vinci created a series of drawings titled 'Study of Cat Movements and Positions', which consists of more than twenty drawings of cats and lions lying a sleep, sitting, playing, and fighting.",
  "Cats must have fat in their diet because they can't produce it on their own.",
  "In Korea and Japan, there is a Cat Cafe where you can go to drink coffee and hang out with cats for hours.",
  "A cat has more bones than a human; humans have 206, but the cat has 230 (some cites list 245 bones, and state that bones may fuse together as the cat ages).",
  "The average cat sleeps between 12-14 hours a day.",
  "Scottish sailer Alexander Selkirk once survived for 4 years on a deserted island thanks to feral cats that protected him from large rats during the night.",
  "Sir Isaac Newton is not only credited with the laws of gravity but is also credited with inventing the cat flap.",
  "The world's richest cat is worth $13 million after his human passed away and left her fortune to him.",
  "Cats, like dogs, are digitigrades. They walk directly on their toes, with the bones of their feet making up the lower part of the visible leg.",
  "Cats, just like people, are subject to asthma. Dust, smoke, and other forms of air pullution in your cat's environment can be troublesome sources of irritation.",
  "Contrary to popular belief, the cat is a social animal. A pet cat will respond and answer to speech, and seems to enjoy human companionship.",
  "An adult cat has 30 teeth, 16 on the top and 14 on the bottom.",
  "Cats is called Kucing in Indonesia.",
  "Asfasasfa.",
  "Cats make about 100 different sounds. Dogs make only about 10.",
  "Domestic cats will try not to drink from a water bowl that is next to their food. This is because in the wild, water next to their kill could be contaminated.",
  "A cat named Emmy lived aboard the RMS Empress of Ireland and she never missed a voyage. On May 28,1914, however, she refused to board. The ship left without her and then sank the following day.",
  "Ailurophile is the word cat lovers are officially called.",
  "Cute.",
  "One un-neutered female cat can, in five years, be responsible for over 20,000 descendants. Female cats can have their first litter as young as six months and can have up to three litters each yearwith five or six kittens in each litter.",
  "A cat can jump up to six times its length.",
  "Cats often overract to unexpected stimuli because of their extremely sensitive nervous system.",
  "Retractable claws are a physical phenomenon that sets cats apart from the rest of the animal kingdom. I n the cat family, only cheetahs cannot retract their claws.",
  "The most traveled cat is Hamlet, who escaped from his carrier while on a flight. He hid for seven weeks behind a panel on the airplane. By the time he was discovered, he had traveled nearly 373,000 miles (600,000 km).",
  "The first breeding pair of Siamese cats arrived in England in 1884.",
  "Cats' eyes shine in the dark because of the tapetum, a reflective layer in the eye, which acts like a mirror.",
  "In tigers and tabbies, the middle of the tongue is covered in backward-pointing spines, used for breaking off and gripping meat.",
  "Statistics indicate that animal lovers in recent years have shown a preference for cats over dogs!",
  "Cats have an average of 24 whiskers, arranged in four horizontal rows on each side.",
  "The Bombay cat breed was developed to resemble a miniature panther.",
  "The Egyptian Mau is the oldest breed of cat, and is the fastest pedigreed cat.",
  "Cats can change their meow to manipulate a human. They often imitate a human baby when they need food, for example.",
  "Female cats are 'polyestrous,' which means they may have many heat periods over the course of a year. A heat period lasts about 4 to 7 days if the female is bred; if she is not, the heat period lasts longer and recurs at regular intervals.",
  "Kittens remain with their mother till the age of 9 weeks.",
  "Owning a cat can reduce the risk of stroke and heart attack by a third.",
  "The cat's tongue has backwards-facing spines about 500 μm long, which are called papillae. These contain keratin which makes them rigid so the papillae act like a hairbrush.",
  "Cats 'knead' because of seperation from their mothers",
  "Adult cats only meow to communicate with humans.",
  "Most cats killed on the road are un-neutered toms, as they are more likely to roam further afield and cross busy roads.",
  "There are 45 Hemingway cats living at the author's former home in Key West, Fla.",
  "The cat's clavicle, or collarbone, does not connect with other bones but is buried in the muscles of the shoulder region. This lack of a functioning collarbone allows them to fit through any opening the size of their head."
}
