-- * _JOKER_VERSION: 0.0.1 ** Please do not modify this line.
--[[----------------------------------------------------------
	Joker - Jokes, Riddles, Fun Facts, & Other Tomfoolery
  ----------------------------------------------------------
  *
  * ADDING YOUR OWN JOKES:
  * Be aware that modifying this file incorrectly could break Joker,
  * so for normal users I recommend just compiling your jokes in the
  * '_MyCustomJokes.lua' file instead.
  *
  * COMPILATION: Dad jokes 
	*
	* SOURCES:
  * https://icanhazdadjoke.com, 
  * Github@15Dkatz/official_joke_api, 
  * Reddit Search, 
  * Reader's Digest
	*
]]--

JokerData = JokerData or {}
JokerData.Config = JokerData.Config or {}

JokerData.Config.Dad = {
  label = "Dad",
  command = "dad",
  nsfw = false,
  joke = true,
  whitelistSlashCommand = true
}

JokerData.Dad = {
  "The magician got mad. He pulled his hare out.",
  "What does a grape say when it gets stepped on? Nothing. It just lets out a little wine.",
  "I used to just crastinate, but then I was so good I became pro at it. -- @manavortex",
  "Employee of the month is a good example of how somebody can be both a winner and a loser at the same time. -- Demetri Martin",
  "It’s not that I’m afraid to die, I just don’t want to be there when it happens. -- Woody Allen",
  "When I was a boy, I laid in my twin sized bed and wondered where my brother was. -- Mitch Hedberg",
  "My drug test came back negative. My dealer sure has some explaining to do.",
  "I think it’s wrong that only one company makes the game Monopoly. -- Steven Wright",
  "The worst time to have a heart attack is during a game of charades. -- Demetri Martin",
  "I have the world's largest collection of seashells, you may have seen it, I keep it scattered on beaches all over.",
  "I want to die peacefully in my sleep, like my grandfather.. Not screaming and yelling like the passengers in his car.",
  "When life gives you melons, you might be dyslexic.",
  "I don’t want to be part of a club that would have me as a member. -- Groucho Marx",
  "Last night, I played poker with Tarot cards … got a full house and 4 people died. -- Steven Wright",
  "My father has schizophrenia, but he’s good people. -- Stewart Francis",
  "Does my wife think I'm a control freak? I haven't decided yet. -- Stewart Francis",
  "I'm on a whisky diet... I've lost three days already! -- Tommmy Cooper",
  "Honesty may be the best policy, but it’s important to remember that apparently, by elimination, dishonesty is the second-best policy. -- George Carlin",
  "Starbucks says they are going to start putting religious quotes on cups. The very first one will say, 'Jesus! This cup is expensive!' -- Conan O'Brien",
  "I had a wonderful childhood, which is tough because it's hard to adjust to a miserable adulthood -- Larry David",
  "Did you hear about the crook who stole a calendar? He got twelve months.",
  "R.I.P boiled water. You will be mist.",
  "Nurse: 'Doctor, there's a patient on line 1 that says he's invisible'. Doctor: 'Well, tell him I can't see him right now.'",
  "Intelligence is like underwear. It is important that you have it, but not necessary that you show it off.",
  "The older I get, the earlier it gets late.",
  "My girlfriend is always stealing my t-shirts and sweaters... But if I take one of her dresses, suddenly 'we need to talk'.",
  "Last night in my dream I was peeing in bed. Dreams do come true, I realized in the morning.",
  "Smoking will kill you... Bacon will kill you... But,smoking bacon will cure it.",
  "Thanks for explaining the word 'many' to me, it means a lot.",
  "Moses had the first tablet that could connect to the cloud.",
  "About a month before he died, my uncle had his back covered in lard. After that, he went down hill fast.",
  "The first computer dates back to Adam and Eve. It was an Apple with limited memory, just one byte. And then everything crashed.",
  "I'm not saying your perfume is too strong. I'm just saying the canary was alive before you got here.",
  "I grew a beard thinking it would say 'Distinguished Gentleman.' Instead, turns out it says, 'Senior Discount, Please!'",
  "At what age is it appropriate to tell my dog that he's adopted?",
  "I tried to explain to my 4-year-old son that it's perfectly normal to accidentally poop your pants, but he's still making fun of me.",
  "I like having conversations with kids. Grownups never ask me what my third favorite reptile is.",
  "Today a man knocked on my door and asked for a small donation towards the local swimming pool. I gave him a glass of water.",
  "I just read that 5,677,145 people got married last year, not to cause any trouble but shouldn't that be an even number?",
  "I think my neighbor is stalking me as she's been googling my name on her computer. I saw it through my telescope last night.",
  "Feeling pretty proud of myself. The Sesame Street puzzle I bought said 3-5 years, but I finished it in 18 months.",
  "My mom said that if I don't get off my computer and do my homework she'll slam my head on the keyboard, but I think she's jokinfjreoiwjrtwe4to8rkljreun8f4ny84c8y4",
  "Before I criticize a man, I like to walk a mile in his shoes. That way, when I do criticize him, I'm a mile away and I have his shoes.",
  "My wife just found out I replaced our bed with a trampoline; she hit the roof.",
  "I just asked my husband if he remembers what today is... Scaring men is easy.",
  "The question isn't at what age I want to retire, it's at what income.",
  "eBay is so useless. I tried to look up lighters and all they had was 13,749 matches.",
  "My dad died when we couldn't remember his blood type. As he died, he kept insisting for us to 'be positive,' but it's hard without him.",
  "I started out with nothing, and I still have most of it.",
  "I always feel better when my doctor says something is normal for my age but then think dying will also be normal for my age at some point.",
  "I would request a last meal of soda and pop rocks so I could die on my own terms.",
  "She wanted a puppy. But I didn't want a puppy. So we compromised and got a puppy.",
  "Did you know that dolphins are so smart that within a few weeks of captivity, they can train people to stand on the very edge of the pool and throw them fish?",
  "People used to laugh at me when I would say 'I want to be a comedian', well nobody's laughing now.",
  "I changed my password to 'incorrect'. So whenever I forget what it is the computer will say 'Your password is incorrect'.",
  "To this day, the boy that used to bully me at school still takes my lunch money. On the plus side, he makes great Subway sandwiches.",
  "When I told the doctor about my loss of memory, he made me pay in advance.",
  "Artificial intelligence is no match for natural stupidity.",
  "TRUE FRIENDSHIP: Walking into a persons house and your wifi connects automatically.",
  "A computer once beat me at chess, but it was no match for me at kick boxing.",
  "I think we should get rid of democracy. All in favor: raise your hand.",
  "That awkward moment when you leave a store without buying anything and all you can think is 'act natural, you're innocent'.",
  "If you're not supposed to eat at night, why is there a light bulb in the refrigerator?",
  "Math Teacher: 'If I have 5 bottles in one hand and 6 in the other hand, what do I have?' Student: 'A drinking problem.'",
  "Light travels faster than sound. This is why some people appear bright until you hear them speak.",
  "I hate people who use big words just to make themselves look perspicacious.",
  "I named my dog 6 miles so I can tell people that I walk 6 miles every single day.",
  "I used to think I was indecisive, but now I'm not too sure.",
  "We just got a fax. At work. We didn't know we had a fax machine. The entire department just stared at it. I poked it with a stick.",
  "One day you're the best thing since sliced bread. The next, you're toast.",
  "Just burned 2,000 calories. That's the last time I leave brownies in the oven while I nap.",
  "I didn't say it was your fault, I said I was blaming you.",
  "Don't you hate it when someone answers their own questions? I do.",
  "I won $3 million on the lottery this weekend so I decided to donate a quarter of it to charity. Now I have $2,999,999.75.",
  "Scientists say the universe is made up of Protons, Neutrons, and Electrons. They forgot to mention Morons.",
  "My email password has been hacked. That's the third time I've had to rename the cat.",
  "I didn't fight my way to the top of the food chain to be a vegetarian.",
  "Life is all about perspective. The sinking of the Titanic was a miracle to the lobsters in the ship's kitchen.",
  "You can make a water-bed more bouncy by using spring water.",
  "Team work is important; it helps to put the blame on someone else.",
  "The man who created autocorrect has died. Resturant in Peacce.",
  "Don't trust atoms, they make up everything.",
  "Did you hear about the semi-colon that broke the law? He was given two consecutive sentences.",
  "To the mathematicians who thought of the idea of zero, thanks for nothing!",
  "Claustrophobic people are more productive thinking out of the box.",
  "Spoiler alert! The milk has been in the fridge for three weeks.",
  "What do you get when you cross a joke with a rhetorical question?",
  "A pun, a play on words, and a limerick walk into a bar. No joke.",
  "Did you hear about the mathematician who's afraid of negative numbers? He will stop at nothing to avoid them!",
  "Why did Beethoven get rid of all his chickens? All they said was 'Bach, Bach Bach'!",
  "C, E-flat, and G walk into a bar. The bartender shows them the door, saying 'Sorry, we don't serve minors!'",
  "A sign at a music shop: 'Gone Chopin, be Back in a minuet!'",
  "What was Beethoven's favorite fruit? Ba-na-na-naaaaaaa!",
  "A photon is going through security. The TSA agent asks if he has any luggage. The photon cooly replies, 'No, I'm traveling light!'",
  "The bartender says 'Sorry, we don't server time travelers here'. A time traveler walks into a bar.",
  "What did the Buddhist say to the hot dog vendor? 'Make me one with everything.'",
  "If you jumped off the bridge in Paris, you'd be in Seine.",
  "A German walks into a bar and asks for a martini. The bartender asks, 'Dry?' The German replies, 'Nein, just one.'",
  "Did you hear about the weekly poker game with Vasco da Gama, Columbus, Erikson, & Pizzaro? They can never seem to beat the straights of Magellan.",
  "If you're American when you go in the bathroom and American when you come out, what are you in the bathroom? European.",
  "What do you call a fish with no eyes? A fsh.",
  "What do you call a can opener that doesn't work? A can't opener!",
  "There are three types of people in the world: those who can count, and those who can't.",
  "Did you hear about the Italian chef who died? He pasta-way.",
  "I sold my vacuum the other day. It really sucks, and all it was doing was collecting dust.",
  "What is Forrest Gump's email password? 1forrest1",
  "Two windmills are standing in a wind farm. One asks, 'What's your favorite music genre?' The other replies, 'I'm a big metal fan.'",
  "Did you hear about the guy who invented the knock knock joke? He won the no-bell prize.",
  "I like elephants. Everythign else is irrelephant.",
  "What's red and bad for your teeth? A brick.",
  "Why does Snoop Dogg use an umbrella? For drizzle.",
  "The astronaut was claustrophobic; he just needed some space.",
  "Noses can't be more than 11 inches long, because then they'd be a foot.",
  "My wedding was so beautiful, even the cake was in tiers!",
  "A dyslexic man walks into a bra...",
  "What do you call a fly with no wings? A walk.",
  "What did the janitor yell when he jumped out of the closet? 'Supplies!'",
  "It's not appropriate to make a 'dad joke' if you are not a dad. It's a faux pa.",
  "What's the most terrifying word in nuclear physics? 'Oops!'",
  "I'm writing a horror screenplay. It starts off with a ringing phone. The person answers, and it's their relative saying 'I have a computer question.'",
  "The other day, my wife asked me to pass her lipstick but I accidentally passed her a glue stick. She still isn't talking to me.",
  "It’s important to have a good vocabulary. If I had known the difference between the words 'antidote' and 'anecdote,' one of my good friends would still be alive.",
  "When ordering food at a restaurant, I asked the waiter how they prepare their chicken. 'Nothing special,' he explained. 'We just tell them they're going to die.'",
  "What's the last thing to go through a fly's head as it hits the windshield of a car going 70mph? Its butt.",
  "What did the fish say when it hit the wall? Dam.",
  "How do you make a tissue dance? You put a little boogie on it.",
  "What's Forrest Gump's password? 1Forrest1",
  "What do you call a belt made out of watches? A waist of time.",
  "Why couldn't the bike standup by itself? It was two tired.",
  "How does a train eat? It goes chew, chew",
  "What do you call a singing Laptop A Dell",
  "How many lips does a flower have? Tulips",
  "How do you organize a space party? You planet.",
  "What kind of shoes does a thief wear? Sneakers",
  "What's the best time to go to the dentist? Tooth hurty.",
  "I should throw away my broken pencil, it's pointless.",
  "Knock knock. Who's there? Cows go. Cows go who? No, cows go moo.",
  "Knock knock. Who's there? Little old lady. Little old lady who? I didn't know you could yodel!",
  "What's the best thing about a Boolean? Even if you're wrong, you're only off by a bit.",
  "What's the object-oriented way to become wealthy? Inheritance",
  "Where do programmers like to hangout? The Foo Bar.",
  "Why did the programmer quit his job? Because he didn't get arrays.",
  "Did you hear about the two silk worms in a race? It ended in a tie.",
  "What do you call a laughing motorcycle? A Yamahahahaha.",
  "A termite walks into a bar and says... 'Is the bar tender here?'",
  "What does C.S. Lewis keep at the back of his wardrobe? Narnia business!",
  "Why do programmers always mix up Halloween and Christmas? Because Oct 31 == Dec 25",
  "A SQL query walks into a bar, walks up to two tables and asks... 'Can I join you?'",
  "How many programmers does it take to change a lightbulb? None that's a hardware problem",
  "If you put a million monkeys at a million keyboards, one of them will eventually write a Java program the rest of them will write Perl",
  "['hip', 'hip'] (hip hip array)",
  "To understand what recursion is... You must first understand what recursion is",
  "There are 10 types of people in this world... Those who understand binary and those who don't",
  "What did the duck say when he bought lipstick? Put it on my bill",
  "What happens to a frog's car when it breaks down? It gets toad away.",
  "did you know the first French fries weren't cooked in France? they were cooked in Greece",
  "Which song would an exception sing? Can't catch me - Avicii",
  "Knock knock. Who's there? Opportunity. That is impossible. Opportunity doesn’t come knocking twice!",
  "Why do Java programmers wear glasses? Because they don't C#",
  "Why did the mushroom get invited to the party? Because he was a fungi.",
  "I'm reading a book about anti-gravity... It's impossible to put down",
  "If you're American when you go into the bathroom, and American when you come out, what are you when you're in there? European",
  "Want to hear a joke about a piece of paper? Never mind...it's tearable",
  "I just watched a documentary about beavers. It was the best dam show I ever saw",
  "If you see a robbery at an Apple Store, does that make you an iWitness?",
  "A ham sandwich walks into a bar and orders a beer. The bartender says, 'Sorry we don't serve food here.'",
  "Why did the Clydesdale give the pony a glass of water? Because he was a little horse",
  "If you boil a clown... Do you get a laughing stock?",
  "Finally realized why my plant sits around doing nothing all day... He loves his pot.",
  "Don't look at the eclipse through a colander. You'll strain your eyes.",
  "I bought some shoes from a drug dealer. I don't know what he laced them with, but I was tripping all day!",
  "Why do chicken coops only have two doors? Because if they had four, they would be chicken sedans",
  "What do you call a factory that sells passable products? A satisfactory",
  "When a dad drives past a graveyard: Did you know that's a popular cemetery? Yep, people are just dying to get in there",
  "Why did the invisible man turn down the job offer? He couldn't see himself doing it",
  "How do you make holy water? You boil the hell out of it",
  "I had a dream that I was a muffler last night. I woke up exhausted!",
  "Why is Peter Pan always flying? Because he neverlands",
  "How do you check if a webpage is HTML5? Try it out on Internet Explorer",
  "What do you call a cow with no legs? Ground beef!",
  "I dropped a pear in my car this morning. You should drop another one, then you would have a pair.",
  "A user interface is like a joke. If you have to explain it then it is not that good.",
  "Knock knock. Who's there? Hatch. Hatch who? Bless you!",
  "What do you call sad coffee? Despresso.",
  "Why did the butcher work extra hours at the shop? To make ends meat.",
  "Did you hear about the hungry clock? It went back four seconds.",
  "Well... That’s a deep subject.",
  "Did you hear the story about the cheese that saved the world? It was legend dairy.",
  "Did you watch the new comic book movie? It was very graphic!",
  "I started a new business making yachts in my attic this year... The sails are going through the roof!",
  "I got hit in the head by a soda can, but it didn't hurt that much... it was a soft drink.",
  "I can't tell if I like this blender... it keeps giving me mixed results.",
  "I wanted to make a reservation at the library, but they were completely booked.",
  "I was gonna tell you a joke about UDP... ...but you might not get it.",
  "The punchline often arrives before the set-up. Do you know the problem with UDP jokes?",
  "Why do C# and Java developers keep breaking their keyboards? Because they use a strongly typed language.",
  "What do you give to a lemon in need? Lemonaid.",
  "Never take advice from electrons. They are always negative.",
  "Hey, dad, did you get a haircut? No, I got them all cut.",
  "What time is it? I don't know... it keeps changing.",
  "A weasel walks into a bar. The bartender says, 'Wow, I've never served a weasel before. What can I get for you?' Pop,goes the weasel.",
  "Bad at golf? Join the club.",
  "Can a kangaroo jump higher than the Empire State Building? Of course. The Empire State Building can't jump.",
  "Can February march? No, but April may.",
  "Can I watch the TV? Yes, but don’t turn it on.",
  "Dad, can you put my shoes on? I don't think they'll fit me.",
  "Did you hear about the bread factory burning down? They say the business is toast.",
  "Did you hear about the chameleon who couldn't change color? They had a reptile dysfunction.",
  "Did you hear about the cheese factory that exploded in France? There was nothing left but de Brie.",
  "Did you hear about the cow who jumped over the barbed wire fence? It was udder destruction.",
  "Did you hear about the guy who invented Lifesavers? They say he made a mint.",
  "Did you hear about the guy who lost the left side of his body? He's all right now.",
  "Did you hear about the kidnapping at school? It's okay, he woke up.",
  "Did you hear about the Mexican train killer? He had loco motives",
  "Did you hear about the new restaurant on the moon? The food is great, but there’s just no atmosphere.",
  "Did you hear about the runner who was criticized? He just took it in stride",
  "Did you hear about the scientist who was lab partners with a pot of boiling water? He had a very esteemed colleague.",
  "Did you hear about the submarine industry? It really took a dive...",
  "Did you hear that David lost his ID in prague? Now we just have to call him Dav.",
  "Did you hear that the police have a warrant out on a midget psychic ripping people off? It reads 'Small medium at large.'",
  "Did you hear the joke about the wandering nun? She was a roman catholic.",
  "Did you hear the news? FedEx and UPS are merging. They’re going to go by the name Fed-Up from now on.",
  "Did you hear the one about the guy with the broken hearing aid? Neither did he.",
  "Did you know crocodiles could grow up to 15 feet? But most just have 4.",
  "What do ghosts call their true love? Their ghoul-friend",
  "Did you know that protons have mass? I didn't even know they were catholic.",
  "Did you know you should always take an extra pair of pants golfing? Just in case you get a hole in one.",
  "Do I enjoy making courthouse puns? Guilty",
  "Do you know where you can get chicken broth in bulk? The stock market.",
  "Do you want a brief explanation of what an acorn is? In a nutshell, it's an oak tree.",
  "Ever wondered why bees hum? It's because they don't know the words.",
  "Have you ever heard of a music group called Cellophane? They mostly wrap.",
  "There is a band called one thousand and twenty three megabytes. They haven't had any gigs yet.",
  "Have you heard the rumor going around about butter? Never mind, I shouldn't spread it.",
  "How are false teeth like stars? They come out at night!",
  "How can you tell a vampire has a cold? They start coffin.",
  "How come a man driving a train got struck by lightning? He was a good conductor.",
  "How come the stadium got hot after the game? Because all of the fans left.",
  "How did Darth Vader know what Luke was getting for Christmas? He felt his presents.",
  "How did the hipster burn the roof of his mouth? He ate the pizza before it was cool.",
  "How do hens stay fit? They always egg-cercise!",
  "How do locomotives know where they're going? Lots of training",
  "How do the trees get on the internet? They log on.",
  "How do you find Will Smith in the snow?  Look for fresh prints.",
  "How do you fix a broken pizza? With tomato paste.",
  "How do you fix a damaged jack-o-lantern? You use a pumpkin patch.",
  "How do you get a baby alien to sleep?  You rocket.",
  "How do you get two whales in a car? Start in England and drive West.",
  "How do you know if there’s an elephant under your bed? Your head hits the ceiling!",
  "How do you make a hankie dance? Put a little boogie in it.",
  "How do you make holy water? You boil the hell out of it.",
  "How do you organize a space party? You planet.",
  "How do you steal a coat? You jacket.",
  "How do you tell the difference between a crocodile and an alligator? You will see one later and one in a while.",
  "How does a dyslexic poet write? Inverse.",
  "How does a French skeleton say hello? Bone-jour.",
  "How does a penguin build it’s house? Igloos it together.",
  "How does a scientist freshen their breath? With experi-mints!",
  "How does the moon cut his hair? Eclipse it.",
  "How many apples grow on a tree? All of them!",
  "How many bones are in the human hand? A handful of them.",
  "How many hipsters does it take to change a lightbulb? Oh, it's a really obscure number. You've probably never heard of it.",
  "How many kids with ADD does it take to change a lightbulb? Let's go ride bikes!",
  "How many optometrists does it take to change a light bulb? 1 or 2? 1... or 2?",
  "How many seconds are in a year? 12. January 2nd, February 2nd, March 2nd, April 2nd.... etc",
  "How many South Americans does it take to change a lightbulb? A Brazilian",
  "How many tickles does it take to make an octopus laugh? Ten-tickles!",
  "How much does a hipster weigh? An instagram.",
  "How was the snow globe feeling after the storm? A little shaken.",
  "Is the pool safe for diving? It deep ends.",
  "Is there a hole in your shoe? No… Then how’d you get your foot in it?",
  "What did the spaghetti say to the other spaghetti? Pasta la vista, baby!",
  "What’s 50 Cent’s name in Zimbabwe? 200 Dollars.",
  "Want to hear a chimney joke? Got stacks of em! First one's on the house",
  "Want to hear a joke about construction? Nah, I'm still working on it.",
  "Want to hear my pizza joke? Never mind, it's too cheesy.",
  "What animal is always at a game of cricket? A bat.",
  "What are the strongest days of the week? Saturday and Sunday...the rest are weekdays.",
  "What biscuit does a short person like? Shortbread. ",
  "What cheese can never be yours? Nacho cheese.",
  "What creature is smarter than a talking parrot? A spelling bee.",
  "What did celery say when he broke up with his girlfriend? She wasn't right for me, so I really don't carrot all.",
  "What did Michael Jackson name his denim store?    Billy Jeans!",
  "What did one nut say as he chased another nut?  I'm a cashew!",
  "What did one plate say to the other plate? Dinner is on me!",
  "What did one snowman say to the other snow man? Do you smell carrot?",
  "What did one wall say to the other wall? I'll meet you at the corner!",
  "What did Romans use to cut pizza before the rolling cutter was invented? Lil Caesars",
  "What did the 0 say to the 8? Nice belt.",
  "What did the beaver say to the tree? It's been nice gnawing you.",
  "What did the big flower say to the littler flower? Hi, bud!",
  "What did the Buffalo say to his little boy when he dropped him off at school? Bison.",
  "What did the digital clock say to the grandfather clock? Look, no hands!",
  "What did the dog say to the two trees? Bark bark.",
  "What did the Dorito farmer say to the other Dorito farmer? Cool Ranch!",
  "What did the fish say when it swam into a wall? Damn!",
  "What did the grape do when he got stepped on? He let out a little wine.",
  "What did the judge say to the dentist? Do you swear to pull the tooth, the whole tooth and nothing but the tooth?",
  "What did the late tomato say to the early tomato? I’ll ketch up",
  "What did the left eye say to the right eye? Between us, something smells!",
  "What did the mountain climber name his son? Cliff.",
  "What did the ocean say to the beach? Thanks for all the sediment.",
  "What did the ocean say to the shore? Nothing, it just waved.",
  "Why don't you find hippopotamuses hiding in trees? They're really good at it.",
  "What did the pirate say on his 80th birthday? Aye Matey!",
  "What did the Red light say to the Green light? Don't look at me I'm changing!",
  "What did the scarf say to the hat? You go on ahead, I am going to hang around a bit longer.",
  "What did the shy pebble wish for? That she was a little boulder.",
  "What did the traffic light say to the car as it passed? Don't look I'm changing!",
  "What did the Zen Buddist say to the hotdog vendor? Make me one with everything.",
  "What do birds give out on Halloween? Tweets.",
  "What do I look like? A JOKE MACHINE!?",
  "What do prisoners use to call each other? Cell phones.",
  "What do vegetarian zombies eat? Grrrrrainnnnnssss.",
  "What do you call a bear with no teeth? A gummy bear!",
  "What do you call a bee that lives in America? A USB.",
  "What do you call a boomerang that won't come back? A stick.",
  "What do you call a careful wolf? Aware wolf.",
  "What do you call a cow on a trampoline? A milk shake!",
  "What do you call a cow with no legs? Ground beef.",
  "What do you call a cow with two legs? Lean beef.",
  "What do you call a crowd of chess players bragging about their wins in a hotel lobby? Chess nuts boasting in an open foyer.",
  "What do you call a dad that has fallen through the ice? A Popsicle.",
  "What do you call a dictionary on drugs? High definition.",
  "What do you call a dog that can do magic tricks? A Labracadabrador.",
  "What do you call a droid that takes the long way around? R2 detour.",
  "What do you call a duck that gets all A's? A wise quacker.",
  "What do you call a fake noodle? An impasta.",
  "What do you call a fashionable lawn statue with an excellent sense of rhythmn? A metro-gnome",
  "What do you call a fat psychic? A four-chin teller.",
  "What do you call a fly without wings? A walk.",
  "What do you call a girl between two posts? Annette.",
  "What do you call a group of disorganized cats? A cat-tastrophe.",
  "What do you call a group of killer whales playing instruments? An Orca-stra.",
  "What do you call a monkey in a mine field? A babooooom!",
  "What do you call a nervous javelin thrower? Shakespeare.",
  "What do you call a pig that knows karate? A pork chop!",
  "What do you call a pig with three eyes? Piiig",
  "What do you call a pile of cats?  A Meowtain.",
  "What do you call a sheep with no legs? A cloud.",
  "What do you call a troublesome Canadian high schooler? A poutine.",
  "What do you call an alligator in a vest? An in-vest-igator!",
  "What do you call an Argentinian with a rubber toe? Roberto",
  "What do you call an eagle who can play the piano? Talonted!",
  "What do you call an elephant that doesn’t matter? An irrelephant.",
  "What do you call an old snowman? Water.",
  "What do you call cheese by itself? Provolone.",
  "What do you call corn that joins the army? Kernel.",
  "What do you call someone with no nose? Nobody knows.",
  "What do you call two barracuda fish?  A Pairacuda!",
  "What do you do on a remote island? Try and find the TV island it belongs to.",
  "What do you do when you see a space man? Park your car, man.",
  "What do you get hanging from Apple trees? Sore arms.",
  "What do you get when you cross a bee and a sheep? A bah-humbug.",
  "What do you get when you cross a chicken with a skunk? A fowl smell!",
  "What do you get when you cross a rabbit with a water hose? Hare spray.",
  "What do you get when you cross a snowman with a vampire? Frostbite.",
  "What do you give a sick lemon? Lemonaid.",
  "What does a clock do when it's hungry? It goes back four seconds!",
  "What does a female snake use for support? A co-Bra!",
  "What does a pirate pay for his corn? A buccaneer!",
  "What does an angry pepper do? It gets jalapeño face.",
  "What happens to a frog's car when it breaks down? It gets toad.",
  "What happens when you anger a brain surgeon? They will give you a piece of your mind.",
  "What has ears but cannot hear? A field of corn.",
  "What is a centipedes's favorite Beatle song?  I want to hold your hand, hand, hand, hand...",
  "What is a tornado's favorite game to play? Twister!",
  "What is a vampire's favorite fruit? A blood orange.",
  "What is a witch's favorite subject in school? Spelling!",
  "What is red and smells like blue paint? Red paint!",
  "What is the difference between ignorance and apathy? I don't know and I don't care.",
  "What is the hardest part about sky diving? The ground.",
  "What is the leading cause of dry skin? Towels",
  "What is the least spoken language in the world? Sign Language",
  "What is the tallest building in the world? The library, it’s got the most stories!",
  "What is this movie about? It is about 2 hours long.",
  "What kind of award did the dentist receive? A little plaque.",
  "What kind of bagel can fly? A plain bagel.",
  "What kind of dinosaur loves to sleep? A stega-snore-us.",
  "What kind of dog lives in a particle accelerator? A Fermilabrador Retriever.",
  "What kind of magic do cows believe in? MOODOO.",
  "What kind of music do planets listen to? Nep-tunes.",
  "What kind of pants do ghosts wear? Boo jeans.",
  "What kind of tree fits in your hand? A palm tree!",
  "What lies at the bottom of the ocean and twitches? A nervous wreck.",
  "What musical instrument is found in the bathroom? A tuba toothpaste.",
  "What time did the man go to the dentist? Tooth hurt-y.",
  "What type of music do balloons hate? Pop music!",
  "What was a more important invention than the first telephone? The second one.",
  "What was the pumpkin’s favorite sport? Squash.",
  "What's black and white and read all over? The newspaper.",
  "What's blue and not very heavy?  Light blue.",
  "What's brown and sticky? A stick.",
  "What's orange and sounds like a parrot? A Carrot.",
  "What's red and bad for your teeth? A Brick.",
  "What's the best thing about elevator jokes? They work on so many levels.",
  "What's the difference between a guitar and a fish? You can tune a guitar but you can't tuna fish!",
  "What's the difference between a hippo and a zippo? One is really heavy, the other is a little lighter.",
  "What's the difference between a seal and a sea lion? An ion! ",
  "What's the worst part about being a cross-eyed teacher? They can't control their pupils.",
  "What's the worst thing about ancient history class? The teachers tend to Babylon.",
  "What’s brown and sounds like a bell? Dung!",
  "What’s E.T. short for? He’s only got little legs.",
  "What’s Forest Gump’s Facebook password? 1forest1",
  "What’s the advantage of living in Switzerland? Well, the flag is a big plus.",
  "What’s the difference between an African elephant and an Indian elephant? About 5000 miles.",
  "When do doctors get angry? When they run out of patients.",
  "When does a joke become a dad joke? When it becomes apparent.",
  "When is a door not a door? When it's ajar.",
  "Where did you learn to make ice cream? Sunday school.",
  "Where do bees go to the bathroom?  The BP station.",
  "Where do hamburgers go to dance? The meat-ball.",
  "Where do rabbits go after they get married? On a bunny-moon.",
  "Where do sheep go to get their hair cut? The baa-baa shop.",
  "Where do you learn to make banana splits? At sundae school.",
  "Where do young cows eat lunch? In the calf-ateria.",
  "Where does batman go to the bathroom? The batroom.",
  "Where does Fonzie like to go for lunch? Chick-Fil-Eyyyyyyyy.",
  "Where does Napoleon keep his armies? In his sleevies.",
  "Where was the Declaration of Independence signed? At the bottom! ",
  "Where’s the bin? I haven’t been anywhere!",
  "Which side of the chicken has more feathers? The outside.",
  "Who did the wizard marry? His ghoul-friend",
  "Who is the coolest Doctor in the hospital? The hip Doctor!",
  "Why are fish easy to weigh? Because they have their own scales.",
  "Why are fish so smart? Because they live in schools!",
  "Why are ghosts bad liars? Because you can see right through them!",
  "Why are graveyards so noisy? Because of all the coffin.",
  "Why are mummys scared of vacation? They're afraid to unwind.",
  "Why are oranges the smartest fruit? Because they are made to concentrate. ",
  "Why are pirates called pirates? Because they arrr!",
  "Why are skeletons so calm? Because nothing gets under their skin.",
  "Why can't a bicycle stand on its own? It's two-tired.",
  "Why can't you use 'Beef stew'as a password? Because it's not stroganoff.",
  "Why can't your nose be 12 inches long? Because then it'd be a foot!",
  "Why can’t you hear a pterodactyl go to the bathroom? The p is silent.",
  "Why couldn't the kid see the pirate movie? Because it was rated arrr!",
  "Why couldn't the lifeguard save the hippie? He was too far out, man.",
  "Why did Dracula lie in the wrong coffin? He made a grave mistake.",
  "Why did Sweden start painting barcodes on the sides of their battleships? So they could Scandinavian.",
  "Why did the A go to the bathroom and come out as an E? Because he had a vowel movement.",
  "Why did the barber win the race? He took a short cut.",
  "Why did the belt go to prison? He held up a pair of pants!",
  "Why did the burglar hang his mugshot on the wall? To prove that he was framed!",
  "Why did the chicken get a penalty? For fowl play.",
  "Why did the coffee file a police report? It got mugged.",
  "Why did the cookie cry? Because his mother was a wafer so long",
  "Why did the cookie cry? It was feeling crumby.",
  "Why did the cowboy have a weiner dog? Somebody told him to get a long little doggy.",
  "Why did the fireman wear red, white, and blue suspenders? To hold his pants up.",
  "Why did the girl smear peanut butter on the road? To go with the traffic jam.",
  "Why did the half blind man fall in the well? Because he couldn't see that well!",
  "Why did the house go to the doctor? It was having window panes.",
  "Why did the kid cross the playground? To get to the other slide.",
  "Why did the man put his money in the freezer? He wanted cold hard cash!",
  "Why did the man run around his bed? Because he was trying to catch up on his sleep!",
  "Why did the melons plan a big wedding? Because they cantaloupe!",
  "Why did the octopus beat the shark in a fight? Because it was well armed.",
  "Why did the opera singer go sailing? They wanted to hit the high Cs.",
  "Why did the scarecrow win an award? Because he was outstanding in his field.",
  "Why did the tomato blush? Because it saw the salad dressing.",
  "Why did the tree go to the dentist? It needed a root canal.",
  "Why did the worker get fired from the orange juice factory? Lack of concentration.",
  "Why didn't the number 4 get into the nightclub? Because he is 2 square.",
  "Why didn’t the orange win the race? It ran out of juice.",
  "Why didn’t the skeleton cross the road? Because he had no guts.",
  "Why do bananas have to put on sunscreen before they go to the beach? Because they might peel!",
  "Why do bears have hairy coats? Fur protection.",
  "Why do bees have sticky hair? Because they use honey combs!",
  "Why do bees hum? Because they don't know the words.",
  "Why do birds fly south for the winter? Because it's too far to walk.",
  "Why do choirs keep buckets handy? So they can carry their tune",
  "Why do crabs never give to charity? Because they’re shellfish.",
  "Why do ducks make great detectives? They always quack the case.",
  "Why do mathematicians hate the U.S.? Because it's indivisible.",
  "Why do pirates not know the alphabet? They always get stuck at 'C'.",
  "Why do pumpkins sit on people’s porches? They have no hands to knock on the door.",
  "Why do scuba divers fall backwards into the water? Because if they fell forwards they’d still be in the boat.",
  "Why do trees seem suspicious on sunny days? Dunno, they're just a bit shady.",
  "Why do valley girls hang out in odd numbered groups? Because they can't even.",
  "Why do wizards clean their teeth three times a day? To prevent bat breath!",
  "Why do you never see elephants hiding in trees? Because they're so good at it.",
  "Why does a chicken coop only have two doors? Because if it had four doors it would be a chicken sedan.",
  "Why does a Moon-rock taste better than an Earth-rock? Because it's a little meteor.",
  "Why does it take longer to get from 1st to 2nd base, than it does to get from 2nd to 3rd base? Because there’s a Shortstop in between!",
  "Why does Norway have barcodes on their battleships? So when they get back to port, they can Scandinavian.",
  "Why does Superman get invited to dinners? Because he is a Supperhero.",
  "Why does Waldo only wear stripes? Because he doesn't want to be spotted.",
  "I'm tired of following my dreams. I'm just going to ask them where they are going and meet up with them later.",
  "Did you hear about the guy whose whole left side was cut off? He's all right now.",
  "Why didn’t the skeleton cross the road? Because he had no guts.",
  "What did one nut say as he chased another nut?  I'm a cashew!",
  "I knew I shouldn't steal a mixer from work, but it was a whisk I was willing to take.",
  "How come the stadium got hot after the game? Because all of the fans left.",
  "Why was it called the dark ages? Because of all the knights. ",
  "A steak pun is a rare medium well done.",
  "Why did the tomato blush? Because it saw the salad dressing.",
  "Did you hear the joke about the wandering nun? She was a roman catholic.",
  "What creature is smarter than a talking parrot? A spelling bee.",
  "I'll tell you what often gets over looked... garden fences.",
  "Why did the kid cross the playground? To get to the other slide.",
  "Why do birds fly south for the winter? Because it's too far to walk.",
  "What is a centipedes's favorite Beatle song?  I want to hold your hand, hand, hand, hand...",
  "My first time using an elevator was an uplifting experience. The second time let me down.",
  "To be Frank, I'd have to change my name.",
  "Slept like a log last night … woke up in the fireplace.",
  "Why does a Moon-rock taste better than an Earth-rock? Because it's a little meteor.",
  "I thought my wife was joking when she said she'd leave me if I didn't stop signing 'I'm A Believer'... Then I saw her face.",
  "Why do trees seem suspicious on sunny days? Dunno, they're just a bit shady.",
  "If at first you don't succeed, sky diving is not for you!",
  "A book just fell on my head. I suppose I only have my shelf to blame.",
  "What did the dog say to the two trees? Bark bark.",
  "Why can't your nose be 12 inches long? Because then it'd be a foot!",
  "Have you ever heard of a music group called Cellophane? They mostly wrap.",
  "What did the mountain climber name his son? Cliff.",
  "Why should you never trust a pig with a secret? Because it's bound to squeal.",
  "Why are mummys scared of vacation? They're afraid to unwind.",
  "I'm a big fan of whiteboards, they're remarkable.",
  "What kind of dinosaur loves to sleep? A stega-snore-us.",
  "What’s Forest Gump’s Facebook password? 1forest1",
  "What kind of tree fits in your hand? A palm tree!",
  "Whenever the cashier at the grocery store asks my dad if he would like the milk in a bag he replies, ‘No, just leave it in the carton!’",
  "I used to be addicted to the hokey pokey, but I turned myself around.",
  "How many tickles does it take to tickle an octopus? Ten-tickles!",
  "Me: If humans lose the ability to hear high frequency volumes as they get older, can my 4 week old son hear a dog whistle?  Doctor: No, humans can never hear that high of a frequency no matter what age they are.  Me: Trick question... dogs can't whistle.",
  "What musical instrument is found in the bathroom? A tuba toothpaste.",
  "My boss told me to attach two pieces of wood together... I totally nailed it!",
  "What was the pumpkin’s favorite sport?  Squash.",
  "Recent survey revealed 6 out of 7 dwarf's aren't happy.",
  "What do you call corn that joins the army? Kernel.",
  "‘Put the cat out’ … ‘I didn’t realize it was on fire",
  "Is there a hole in your shoe? No… Then how’d you get your foot in it?",
  "Every night at 11:11, I make a wish that someone will come fix my broken clock.",
  "Two muffins were sitting in an oven, and the first looks over to the second, and says, 'man, it’s really hot in here'. The second looks over at the first with a surprised look, and answers, 'WHOA, a talking muffin!'",
  "Did you hear that the police have a warrant out on a midget psychic ripping people off? It reads 'Small medium at large.'",
  "Just read a few facts about frogs. They were ribbiting.",
  "Two satellites decided to get married. The wedding wasn't much, but the reception was incredible.",
  "They tried to make a diamond shaped like a duck. It quacked under the pressure.",
  "Where’s the bin? Dad: I haven’t been anywhere!",
  "Why do bears have hairy coats? Fur protection.",
  "What do you get when you cross a bee and a sheep? A bah-humbug. ",
  "What did one snowman say to the other snow man? Do you smell carrot?",
  "Why do bees hum? Because they don't know the words.",
  "What do you call a troublesome Canadian high schooler? A poutine.",
  "A magician was driving down the street and then he turned into a driveway.",
  "Don't trust atoms. They make up everything.",
  "If you walk into a forest and cut down a tree, but the tree doesn't understand why you cut it down, do you think it's stumped?",
  "Where do bees go to the bathroom?  The BP station.",
  "Why did the tree go to the dentist? It needed a root canal.",
  "It was raining cats and dogs the other day. I almost stepped in a poodle.",
  "Why do bananas have to put on sunscreen before they go to the beach? Because they might peel!",
  "What do you call a bee that lives in America? A USB.",
  "I was wondering why the frisbee was getting bigger, then it hit me.",
  "I couldn't figure out how the seat belt worked. Then it just clicked.",
  "What do you call a dad that has fallen through the ice? A Popsicle.",
  "Two parrots are sitting on a perch. One turns to the other and asks, 'do you smell fish?'",
  "Bad at golf? Join the club.",
  "What do you call a pile of cats?  A Meowtain.",
  "How do hens stay fit? They always egg-cercise!",
  "Can a kangaroo jump higher than the Empire State Building? Of course. The Empire State Building can't jump.",
  "What do you give a sick lemon? Lemonaid.",
  "What do you call an old snowman? Water.",
  "I just got fired from a florist, apparently I took too many leaves.",
  "Why don’t skeletons ever go trick or treating? Because they have nobody to go with.",
  "What does a female snake use for support? A co-Bra!",
  "'Dad, I'm cold.' 'Go stand in the corner, I hear it's 90 degrees.'",
  "Child: Dad, make me a sandwich. Dad: Poof! You're a sandwich.",
  "Why are graveyards so noisy? Because of all the coffin.",
  "What kind of bagel can fly? A plain bagel.",
  "How many apples grow on a tree? All of them!",
  "What do you call a careful wolf? Aware wolf.",
  "I was just looking at my ceiling. Not sure if it’s the best ceiling in the world, but it’s definitely up there.",
  "Why do valley girls hang out in odd numbered groups? Because they can't even.",
  "'My Dog has no nose.' 'How does he smell?' 'Awful'",
  "What do you call a cow with no legs? Ground beef.",
  "Why did the half blind man fall in the well? Because he couldn't see that well!",
  "As I suspected, someone has been adding soil to my garden. The plot thickens.",
  "It’s hard to explain puns to kleptomaniacs, because they take everything literally.",
  "It's difficult to say what my wife does, she sells sea shells by the sea shore.",
  "Why did Dracula lie in the wrong coffin? He made a grave mistake.",
  "What did one plate say to the other plate? Dinner is on me!",
  "what do you call a dog that can do magic tricks? a labracadabrador",
  "Doctor: Do you want to hear the good news or the bad news? Patient: Good news please. Doctor: we're naming a disease after you.",
  "I met an atheist who worked for a charity the other day. She said it was a non-prophet organisation.",
  "What do you call a monkey in a mine field? A babooooom! ",
  "I cut my finger cutting cheese. I know it may be a cheesy story but I feel grate now.",
  "How do you steal a coat? You jacket.",
  "Why don't you find hippopotamuses hiding in trees? They're really good at it.",
  "I’m reading a book on the history of glue – can’t put it down.",
  "Construction workers are great at throwing parties. They raise the roof.",
  "Just watched a documentary about beavers. It was the best dam show I’ve ever seen.",
  "Why do choirs keep buckets handy? So they can carry their tune",
  "Did you hear about the kidnapping at school? It's ok, he woke up.",
  "You will never guess what Elsa did to the balloon. She let it go.",
  "You can't run through a camp site. You can only ran, because it's past tents.",
  "They're making a movie about clocks. It's about time",
  "I’ve just been reading a book about anti-gravity, it’s impossible to put down!",
  "Archaeology really is a career in ruins.",
  "I was going to get a brain transplant, but I changed my mind.",
  "Why can't you use 'Beef stew' as a password? Because it's not stroganoff.",
  "Why couldn't the lifeguard save the hippie? He was too far out, man.",
  "Some people say that I never got over my obsession with Phil Collins. But take a look at me now.",
  "Why did the girl smear peanut butter on the road? To go with the traffic jam.",
  "The rotation of earth really makes my day.",
  "How much does a hipster weigh? An instagram.",
  "A woman is on trial for beating her husband to death with his guitar collection. Judge says, ‘First offender?’ She says, ‘No, first a Gibson! Then a Fender!’",
  "I saw an ad in a shop window, 'Television for sale, $1, volume stuck on full', I thought, 'I can't turn that down'.",
  "What kind of dog lives in a particle accelerator? A Fermilabrador Retriever.",
  "What's blue and not very heavy?  Light blue.",
  "I was so proud when I finished the puzzle in six months, when on the side it said three to four years.",
  "Where did you learn to make ice cream? Sunday school.",
  "A quick shoutout to all of the sidewalks out there... Thanks for keeping me off the streets.",
  "Where does Napoleon keep his armies? In his sleevies.",
  "Leather is great for sneaking around because it's made of hide.",
  "People are making apocalypse jokes like there’s no tomorrow.",
  "What is the tallest building in the world? The library – it’s got the most stories!",
  "What kind of magic do cows believe in? MOODOO.",
  "I just broke my guitar. It's okay, I won't fret",
  "How many kids with ADD does it take to change a lightbulb? Let's go ride bikes!",
  "Where do hamburgers go to dance? The meat-ball.",
  "Did you know that ghosts call their true love their ghoul-friend?",
  "What do you call a cow with two legs? Lean beef.",
  "What did the big flower say to the littler flower? Hi, bud!",
  "Why do pumpkins sit on people’s porches?  They have no hands to knock on the door.",
  "Who is the coolest Doctor in the hospital? The hip Doctor!",
  "Why was ten scared of seven? Because seven ate nine.",
  "What do you get when you cross a rabbit with a water hose? Hare spray.",
  "I applied to be a doorman but didn't get the job due to lack of experience. That surprised me, I thought it was an entry level position.",
  "I knew a guy who collected candy canes, they were all in mint condition",
  "Why does a chicken coop only have two doors? Because if it had four doors it would be a chicken sedan.",
  "'I'll call you later.' Don't call me later, call me Dad.",
  "Why did the teddy bear say 'no' to dessert? Because she was stuffed.",
  "Breaking news! Energizer Bunny arrested – charged with battery.",
  "How many bones are in the human hand? A handful of them.",
  "A red and a blue ship have just collided in the Caribbean. Apparently the survivors are marooned.",
  "I've just written a song about a tortilla. Well, it is more of a rap really.",
  "Can February march? No, but April may.",
  "So a duck walks into a pharmacy and says 'Give me some chap-stick… and put it on my bill'",
  "Egyptians claimed to invent the guitar, but they were such lyres.",
  "Toasters were the first form of pop-up notifications.",
  "What is a witch's favorite subject in school? Spelling!",
  "What do you call a crowd of chess players bragging about their wins in a hotel lobby? Chess nuts boasting in an open foyer.",
  "Which side of the chicken has more feathers? The outside.",
  "Remember, the best angle to approach a problem from is the 'try' angle.",
  "Why are fish easy to weigh? Because they have their own scales.",
  "What did the scarf say to the hat? You go on ahead, I am going to hang around a bit longer.",
  "What is the worst combination of two sicknesses? Diarrhea and Alzheimers. You’re running, but you don’t know where.",
  "Do you know what's cool? Winter.",
  "What fish is the best fighter? The swordfish.",
  "I lost some weight last month. But now it found me again.",
  "Do you know why I can’t be buried in a cemetery? Because I'm alive.",
  "'Dad, did you get a haircut?' 'No I got them all cut.'",
  "Today, my son asked 'Can I have a book mark?' and I burst into tears. 11 years old and he still doesn't know my name is Brian.",
  "My wife is really mad at the fact that I have no sense of direction. So I packed up my stuff and right.",
  "How do you make holy water? You boil the hell out of it.",
  "I bought some shoes from a drug dealer. I don't know what he laced them with, but I was tripping all day!",
  "The secret service isn't allowed to yell 'Get down!' anymore when the president is about to be attacked. Now they have to yell 'Donald, duck!'",
  "I'm reading a book about anti-gravity. It's impossible to put down!",
  "What do you call someone with no body and no nose? Nobody knows.",
  "I ordered a chicken and an egg from Amazon. I’ll let you know.",
  "What is the least spoken language in the world? Sign language",
  "My daughter screeched, 'Daaaaaad, you haven't listened to one word I've said, have you!?' What a strange way to start a conversation with me...",
  "A slice of apple pie is $2.50 in Jamaica and $3.00 in the Bahamas. These are the pie rates of the Caribbean.",
  "When a dad drives past a graveyard: Did you know that's a popular cemetery? Yep, people are just dying to get in there!",
  "My friend keeps saying 'cheer up man it could be worse, you could be stuck underground in a hole full of water.' I know he means well.",
  "Justice is a dish best served cold, if it were served warm it would be justwater.",
  "The fattest knight at King Arthur’s round table was Sir Cumference. He acquired his size from too much pi.",
  "Why can't you hear a pterodactyl go to the bathroom? Because the pee is silent.",
  "What does a zombie vegetarian eat? 'GRRRAAAAAIIIINNNNS!'",
  "Due to the method by which most vampires are depicted sucking the blood of their victims, you could say they are also neck romancers.",
  "If all you’re getting out of a relationship is sex you’re getting screwed.",
  "Game of Thrones is going to definitively answer the question whether it's better to have a bad ending (the show) or no ending at all (the books).",
  "If IKEA sold cars, imagine the size of the assembly manual - not to mention driving on a bumpy road in a car assembled with wooden dowels.",
  "Witches have black cats because if they had white cats, they would have white cat hair all over their clothes.",
  "Why do cows have hooves? Because they lack-toes.",
  "Why didn't the skeleton cross the road? Because he didn't have the guts.",
  "Did you hear about the invention of the shovel? It was groundbreaking.",
  "Why wasn't the pirate able to learn the alphabet? Because he kept getting lost at C",
  "Glass coffins.. Will they be popular? Remains to be seen!",
  "I hate Russian dolls, they're so full of themselves!",
  "What does a microscopic cow say? Mu.",
  "Where do fish keep their money? In the riverbank.",
  "A truck carrying wigs crashed today, police are combing the area.",
  "Why did Cinderella get kicked from the football team? Because she kept running from the ball.",
  "I tried to catch fog once... I mist.",
  "I went to a zoo the other day and saw a loaf in a cage. It was bread in captivity.",
  "I've often heard that 'icy' is the easiest word to spell. Looking at it now, I see why.",
  "I'm thinking of selling vegetables for a living. I just hope the celery will be good.",
  "I went to the zoo the other day, but they only had one animal. It was a shitzu.",
  "A blind man walks into a bar.  And a table.  And a chair.",
  "The past, the present, and the future walked into a bar. It was tense.",
  "What do you call two crows on a branch?  Attempted Murder.",
  "A Neutron walks into a bar and asks,'How much for a drink?' The bartender responds, 'For you, no charge!'",
  "How do you kill a circus clown? Go for the juggler.",
  "Dogs can't operate MRI scans, but catscan.",
  "Turning vegan would be a big missed steak.",
  "A truck carrying Scrabble board games rolled over today. That's the word on the street.",
  "What did the guy wear to the tea party? A Tea shirt.",
  "I had a fear of hurdles, but I got over it.",
  "Waking up this morning was an eye-opening experience.",
  "Sleeping comes so naturally to me, I can do it with my eyes closed.",
  "To the guy that stole my anti-depressants: I hope you're happy now.",
  "I had to quit my job at the shoe recycling factory. It was just sole destroying.",
  "I used to be a banker, but over time I lost interest.",
  "The girl quit her job at the donut factory because she was fed up with the hole business.",
  "What type of shirt does an astronaut wear? Apollo shirt.",
  "A friend of mine tried to annoy me with bird puns, but soon I realised that toucan play at that game.",
  "Why did the bee get married? Because he found his honey.",
  "What would bears be without bees? Ears.",
  "Cuddling a cat usually leaves me feline good.",
  "What are twins' favourite fruits? Pears.",
  "How do you capture a skeleton? You use a rib-cage.",
  "Never date a tennis player. Love means nothing to them.",
  "Somebody stole my Thesaurus, I don't have any words to tell you how angry I am.",
  "I wondered why the baseball got bigger. Then it hit me.",
  "I'm not a huge fan of archery. It has too many drawbacks.",
  "My tennis opponent was not happy with my serve. He kept returning it.",
  "I can't understand why people are so bothered about me not knowing what the word 'apocalypse' means. It's not like its the end of the world!",
  "Don't spell 'part' backwards. It's a trap!",
  "Yesterday I ate some food colouring. The doctor says I'm OK, but I feel like I've dyed a little inside.",
  "Don't waste your time trying to eat a clock. It's very time consuming.",
  "It's a lengthy article on Japanese sword fighters, but I can Samurais it for you.",
  "Don't interrupt someone working intently on a puzzle. Chances are, you'll hear some crosswords.",
  "What do you call a bee that cannot make up its mind? A Maybee.",
  "My ex called me average, but she was just being mean.",
  "My chemistry teacher threw natrium-chloride at me. It was a-salt.",
  "A girl at a vegetarian bar said she knew me, but I never met herbivore.",
  "What happens to chemists when they die? We Barium.",
  "I gave my dead batteries away, free of charge of course.",
  "How did the picture end up in jail? It was framed.",
  "My friend thought I would never be able to make a car out of spaghetti. You should've seen her face when I drove pasta.",
  "What should a lawyer always wear to a court? A good lawsuit.",
  "I'm so glad I know sign language. It can come in pretty handy.",
  "Time flies like an arrow. Fruit flies like a banana.",
  "Stayed up all night wondering where the sun had gone, then it dawned on me.",
  "Haunted French pancakes give me the crepes.",
  "Yesterday a clown held the door for me. It was such a nice jester.",
  "I really hate my job at the can crushing factory. It's soda pressing.",
  "A man sued an airline company after it lost his luggage. Sadly, he lost his case.",
  "The machine at the coin factory suddenly stopped working without a reason. It doesn't make any cents.",
  "I dont have enough funds to open my bakery, I need more dough.",
  "6:30 is the best time on a clock... hands down.",
  "I dislike jazz and classical music, it's full of sax and violins.",
  "The furniture guy from last night keeps annoying me, I just wanted one night stand.",
  "I was going to make myself a belt out of watches, but then I realised it would just be a waist of time.",
  "Need to build an ark? I Noah guy.",
  "What cheese can you use to hide a horse? Mascarpone.",
  "What cheese is made backwards? Edam.",
  "Spring is here! I got so excited I wet my plants!",
  "I used to have a job at a calendar factory but I got the sack because I took a couple of days off.",
  "5/4 of people admit that they're bad with fractions.",
  "Two guys walk into a bar, the third one ducks.",
  "Did you hear about the circus fire? It was in tents!",
  "What do sprinters eat before a race? Nothing, they fast.",
  "I'm only familiar with 25 letters in the English language. I don't know why.",
  "You know what the loudest pet you can get is? A trumpet.",
  "I was interrogated over the theft of a cheese toastie. Man, they really grilled me.",
  "What do you call a deer with no eyes? No idea!",
  "Why can't you hear a pterodactyl go to the bathroom? Because the p is silent.",
  "I wasn't happy with the velcro I bought. It was a total ripoff",
  "How does Moses make his tea? Hebrews it.",
  "Seven days without a pun makes one weak.",
  "I can't stand being in a wheelchair."
}
