--[[----------------------------------------------------------
	Joker - Jokes, Riddles, Fun Facts, & Other Tomfoolery
	----------------------------------------------------------
  * COMPILATION: Edgy/Explicit jokes (user is warned prior to first use)
	*
	* SOURCES:
  * Reddit Search, 
  * Google Search
	*
]]--

JokerData = JokerData or {}

JokerData.Edgy = {
  "What is worse than ants in your pants? Uncles!",
  "It's sad that a family can be torn apart by something as simple as wild dogs. -- Jack Handey",
  "The problem isn't that obesity runs in your family. The problem is no one runs in your family.",
  "I tried to change my password to penis but they said it was too short.",
  "There’s no such thing as addiction, there’s only things that you enjoy doing more than life. -- Doug Stanhope",
  "I had to stop drinking, cause I got tired of waking up in my car driving 90. -- Richard Pryor",
  "I asked my North Korean friend how it was there, he said he couldn't complain.",
  "A doctor tells a woman she can no longer touch anything alcoholic. So she gets a divorce.",
  "Life without women would be a pain in the ass, literally.",
  "Alcohol is a perfect solvent: It dissolves marriages, families and careers.",
  "Anal intercourse is for assholes.",
  "I find it ironic that the colors red, white, and blue stand for freedom until they are flashing behind you.",
  "The reason a dog has so many friends is that he wags his tail instead of his tongue.",
  "An old teacher asked her student, 'If I say, 'I am beautiful,' which tense is that?' The student replied, 'It is obviously past.'",
  "A little boy asked his father, 'Daddy, how much does it cost to get married?' Father replied, 'I don't know son, I'm still paying.'",
  "A Mexican magician was doing a magic trick. He said, Uno, Dose, and then disappeared without a trace.",
  "You have two parts of brain, 'left' and 'right'. In the left side, there's nothing right. In the right side, there's nothing left.",
  "A recent finding by statisticians shows the average human has one breast and one testicle.",
  "What do you call a psychic little person who has escaped from prison? A small medium at large!",
  "Three fish are in a tank. One asks the others, 'How do you drive this thing?'",
  "Did you know the first French fries weren't actually cooked in France? They were cooked in Greece.",
  "Me: 'How do I look?' Partner: 'With your eyes.'",
  "What's the best part about living in Switzerland? I don't know, but the flag is a big plus!",
  "Have you heard that rumor about butter? Erm, never mind, I shouldn't be spreading it.",
  "Whenever someone calls me ugly, I get super sad and hug them, because I know how tough life is for the visually impaired.",
  "What do you call a black guy who flies a plane? A pilot, you fucking racist.",
  "What's better than winning a gold medal at the special olympics? Not being retarded!",
  "What's the best way to get a Jewish girl's number? Pull up her sleeve...",
  "What's the best thing about fucking 21 year olds? There's twenty of them!",
  "How many emo kids does it take to change a lightbulb? None. They just sit in the dark and cry.",
  "I wish my lawn were emo, so that it'd cut itself.",
  "What you do call a musician who doesn't have a girlfriend? Homeless.",
  "What's the difference between Jesus and a painting of Jesus? It only takes one nail to hang the painting.",
  "What do you get when you cross a bunny and a Rottweiler? Just the Rottweiler",
  "Give a man a match, and he’ll be warm for a few hours. Set a man on fire, and he will be warm for the rest of his life.",
  "I asked a pretty, young homeless woman if I could take her home. She smiled at me and said yes. The look on her face soon changed, however, when I walked off with her cardboard box.",
  "My elderly relatives liked to tease me at weddings, saying, 'You’ll be next!' They soon stopped though, once I started doing the same to them at funerals.",
  "A blind woman tells her boyfriend that she’s seeing someone. It’s either really terrible news or really great news.",
  "I was digging in our garden when I found a chest full of gold coins. I was about to run straight home to tell my husband about it, but then I remembered why I was digging in our garden.",
  "Even people who are good for nothing have the capacity to bring a smile to your face. For instance, when you push them down the stairs.",
  "One man’s trash is another man’s treasure. Wonderful saying, horrible way to find out you were adopted.",
  "I visited my friend at his new house. He told me to make myself at home. So I threw him out. I hate having visitors.",
  "My son, who’s into astronomy, asked me how stars die. 'Usually an overdose, son,' I told him.",
  "What did Kermit the frog say at Jim Henson’s funeral? Nothing.",
  "My girlfriend’s dog died, so I tried to cheer her up by getting her an identical one. It just made her more upset. She screamed at me, 'What am I supposed to do with two dead dogs?'",
  "What’s yellow and can’t swim? A bus full of children.",
  "I'll never forget my Granddad’s last words to me just before he died: 'Are you still holding the ladder?'",
  "It turns out a major new study recently found that humans eat more bananas than monkeys. It’s true. I can’t remember the last time I ate a monkey.",
  "Today was a terrible day. My ex got hit by a bus, AND I lost my job as a bus driver!",
  "What was David Bowie's last hit? Probably heroin.",
  "What do you call a deaf gynecologist? A lip reader.",
  "What did the elephant say to the naked man? 'How do you breathe through that tiny thing?'",
  "Why are orphans unable to play baseball? They've never known what home is.",
  "I tried to add Paul Walker on Xbox, but he's always in the dashboard.",
  "What is cold and stands under a street lamp? A frostitute.",
  "Problems sleeping? Cut the legs of your bed. You'll sleep deeper.",
  "Why does Santa Claus have such a big sack? He only comes once a year.",
  "What’s the difference between a hooker and a drug dealer? A hooker can wash her crack and resell it.",
  "What does the sign on an out-of-business brothel say? Beat it, we're close.",
  "What’s the difference between a G-spot and a golf ball? Men will actually search for a golf ball.",
  "What do the Mafia and pussies have in common? One slip of the tongue, and you’re in deep shit.",
  "What did the banana say to the vibrator? Why are *you* shaking? She’s gonna *eat* me!",
  "Why does Dr. Pepper come in a bottle? Because his wife died.",
  "What’s the difference between a Catholic priest and a zit? A zit will wait until you’re twelve before it comes on your face.",
  "What’s the best part about gardening? Getting down and dirty with your hoes.",
  "What do you call the useless piece of skin on a dick? The man.",
  "Why do vegetarians give good head? Because they’re used to eating nuts.",
  "How does Jesus make his coffee? Hebrews it.",
  "How do you find Will Smith in the snow? You look for the fresh prints.",
  "Why is there air conditioning in hospitals? To keep the vegetables cool and fresh.",
  "'Racecar' backwards is 'racecar'. 'Racecar' sideways is how Paul Walker died."
}
