-- * _JOKER_VERSION: 0.0.1 ** Please do not modify this line.
--[[----------------------------------------------------------
	Joker - Jokes, Riddles, Fun Facts, & Other Tomfoolery
  ----------------------------------------------------------
  *
  * ADDING YOUR OWN JOKES:
  * Be aware that modifying this file incorrectly could break Joker,
  * so for normal users I recommend just compiling your jokes in the
  * '_MyCustomJokes.lua' file instead.
  *
  * COMPILATION: Cheesy pickup lines
  *
  * INCLUDES MULTIPLE!
  * Joker.PickupLines{}     - Cheesy and cute (mostly clean),
  * Joker.PickupLinesXXX{}  - Adult/R-Rated,
  * Joker.PickupLinesHP{}   - Harry Potter 
	*
  * SOURCES:
  
	* http://jokes4us.com,
	* http://laggfagg.com,
	* http://mashable.com,
  * http://buzzfeed.com,
  * Reddit Search, 
  * Google Search
]]--

JokerData = JokerData or {}
JokerData.Config = JokerData.Config or {}

JokerData.Config.PickupLines = {
  command = "pickup",
  label = "Pickup Lines",
  nsfw = false,
  joke = true,
  usePrefix = true,
  whitelistSlashCommand = true
}

JokerData.Config.PickupLinesXXX = {
  command = "pickup-xxx",
  label = "Pickup Lines (Adult)",
  nsfw = true,
  joke = true,
  usePrefix = true,
  whitelistSlashCommand = true
}

JokerData.Config.PickupLinesHP = {
  command = "pickup-hp",
  label = "Pickup Lines (Harry Potter)",
  joke = true,
  nsfw = false,
  usePrefix = true,
  whitelistSlashCommand = true
}

-- Cheesy and cute (mostly clean) lines
JokerData.PickupLines = {
  "Can I have your picture so I can show Santa what I want for Christmas?",
  "Are you a magician? Because whenever I look at you, everyone else disappears!",
  "Was your dad a boxer? Because damn, you’re a knockout!",
  "Is there an airport nearby or is it my heart taking off?",
  "Are you French because Eiffel for you.",
  "Is that a mirror in your pocket? Cause I can see myself in your pants!",
  "Are you religious? Cause you’re the answer to all my prayers.",
  "Hey, tie your shoes! I don’t want you falling for anyone else.",
  "You must be Jamaican, because Jamaican me crazy.",
  "What has 36 teeth and holds back the Incredible Hulk? My zipper.",
  "Somebody call the cops, because it’s got to be illegal to look that good!",
  "I must be a snowflake, because I've fallen for you.",
  "I know you're busy today, but can you add me to your to-do list?",
  "If you were a steak you would be well done.",
  "Hello, I'm a thief, and I'm here to steal your heart.",
  "Are you cake? Cause I want a piece of that.",
  "My love for you is like diarrhoea, I just can't hold it in.",
  "Are you lost ma'am? Because heaven is a long way from here.",
  "There is something wrong with my cell phone. It doesn't have your number in it.",
  "If you were a library book, I would check you out.",
  "Are you a cat because I'm feline a connection between us",
  "If I were to ask you out on a date, would your answer be the same as the answer to this question?",
  "If nothing lasts forever, will you be my nothing?",
  "I'm new in town. Could you give me directions to your apartment?",
  "I must be in a museum, because you truly are a work of art.",
  "You spend so much time in my mind, I should charge you rent.",
  "My lips are like skittles. Wanna taste the rainbow?",
  "Well, here I am. What were your other two wishes?",
  "Are you from Tennessee? Because you're the only 10 I see!",
  "Are you a beaver? Cause daaaaaaaaam!",
  "Life without you is like a broken pencil... pointless.",
  "Do you want to see a picture of a beautiful person? (hold up a mirror)",
  "Is your body from McDonald's? Cause I'm lovin' it!",
  "cheesy gravity pick up line",
  "Even if there wasn't gravity on earth, I'd still fall for you.",
  "Roses are red, violets are blue, how would you like it if I came home with you?",
  "I wish I were cross-eyed so I can see you twice",
  "We're not socks. But I think we'd make a great pair.",
  "Your lips look so lonely…Would they like to meet mine?",
  "Are you a parking ticket? ‘Cause you’ve got fine written all over you.",
  "Thank god I'm wearing gloves because you are too hot to handle.",
  "If a fat man puts you in a bag at night, don't worry I told Santa I wanted you for Christmas.",
  "I'm no photographer, but I can picture us together.",
  "Do your legs hurt from running through my dreams all night?",
  "Pinch me, you’re so fine I must be dreaming.",
  "If you were a chicken, you'd be impeccable.",
  "How much does a polar beat weight? Enough to break the ice!",
  "Are you a 90 degree angle? Cause you are looking right!",
  "Nice to meet you, I’m (your name) and you are... gorgeous!",
  "If I were a transplant surgeon, I’d give you my heart.",
  "Are you Israeli? Cause you Israeli hot.",
  "On a scale from 1 to 10, you're a 9... And I'm the 1 you need.",
  "Did it hurt? When you fell out of heaven?",
  "If I could rearrange the alphabet I would put U and I together.",
  "Remember me? Oh, that’s right, I’ve met you only in my dreams.",
  "Is your name Google? Because you've got everything I'm searching for.",
  "Your hand looks heavy. Here, let me hold it for you.",
  "I’ve been wondering, do your lips taste as good as they look.",
  "Are you from Starbucks because I like you a latte.",
  "Are you a banana because I find you a peeling.",
  "Do you like vegetables because I love you from my head tomatoes.",
  "Have you been to the doctor's lately? Cause I think you're lacking some vitamin me.",
  "Do you generate electricity with water through the process of hydro power? Because dammmm.",
  "Do you like science because I've got my ion you.",
  "Are you my appendix? Because I don't understand how you work but this feeling in my stomach makes me want to take you out.",
  "Funny pick up line about free clothing",
  "Do you like sales? Because if you're looking for a good one, clothing is 100% off at my place.",
  "I know this is going to sound cheesy, but I think you're the gratest.",
  "If you were a triangle you'd be acute one.",
  "Does your left eye hurt? Because you’ve been looking right all day.",
  "My feet are getting cold… because you’ve knocked my socks off.",
  "Wow, when god made you he was showing off.",
  "If beauty were time, you’d be eternity.",
  "Is your name Wi-fi? Because I'm really feeling a connection.",
  "If looks could kill, you'd be a weapon of mass destruction.",
  "Do you have a tan, or do you always look this hot?",
  "Can I follow you home? Cause my parents always told me to follow my dreams.",
  "If I were a cat I'd spend all 9 lives with you.",
  "Are you a camera? Because every time I look at you, I smile.",
  "Are you from Japan cause I'm trying to get in Japanties.",
  "If you were a fruit you'd be a fineapple.",
  "I'll give you a kiss. If you don't like it, you can return it.",
  "Did you swallow magnets? Cause you're attractive.",
  "Are you from China? Because I'm China get your number.",
  "Do you have a name, or can I call you mine?",
  "Are you craving Pizza? Because I’d love to get a pizz-a you",
  "Wouldn't we look cute on a wedding cake together.",
  "Would you grab my arm so I can tell my friends I've been touched by an angel?",
  "Kiss me if I'm wrong, but dinosaurs still exist, right?",
  "Is your dad a terrorist? Because you are the bomb.",
  "You must be a ninja, because you snuck into my heart",
  "Can you pinch me, because you're so fine I must be dreaming.",
  "I may not be a genie, but I can make all your wishes come true!",
  "Are you Australian? Because you meet all of my koala-fications.",
  "I’m not drunk, I’m just intoxicated by you.",
  "If I followed you home, would you keep me?",
  "If you were words on a page, you’d be fine print.",
  "Are you a keyboard ? Because you are my type.",
  "There is something wrong with my phone. Could you call it for me to see if it rings?",
  "I've seem to have lost my number, can I have yours?",
  "cute and funny pick up line about flowers",
  "If I had a garden I’d put your tulips and my tulips together",
  "Did you hear of the new disease called beautiful, I think you're infected.",
  "I thought Happiness starts with H. But why does mine starts with U.",
  "If you were a vegetable you'd be a cutecumber.",
  "You know what you would really look beautiful in? My arms.",
  "My mom thinks I'm gay, can you help me prove her wrong?",
  "I want someone to look at me the way I look at chocolate cake.",
  "Is it hot in here or is it just you?",
  "Are you going to kiss me or do I have to lie to my diary?",
  "Feel my t-shirt, it’s made of boyfriend material.",
  "You must be a magician, because every time I look at you, everyone else disappears.",
  "Your name must be Coca Cola, because you're so-da-licious.",
  "You're like a dictionary... you add meaning to my life.",
  "My doctor says I'm lacking vitamin U.",
  "Did your licence get suspended for driving all these guys crazy?",
  "funny love up line about love",
  "Do you believe in love at first sight or should I walk past again?",
  "When a penguin finds a mate they stay with them for the rest of their life. Will you be my penguin?",
  "Can I take a picture of you so santa knows what I want for christmas?",
  "I'm new in town, could you give me directions to your apartment?",
  "I'll cook you dinner, if you cook me breakfast",
  "What does it feel like to be the most beautiful girl in the room?",
  "Good thing I just bought term life insurance … because I saw you and my heart stopped!",
  "If I had a dollar for every time I thought of you, I’d be in a higher tax bracket.",
  "Hey, my name’s Microsoft. Can I crash at your place tonight?",
  "Was that an earthquake or did you just rock my world?",
  "You’re so sweet, you’re giving me a toothache.",
  "Roses are red, bananas are yellow, wanna go out with a nice little fellow?",
  "If you're here, who's running heaven?",
  "Do you have a name? Or can I call you mine?",
  "Let's commit the perfect crime. I'll steal your heart and you can steal mine.",
  "Where do you hide your halo?",
  "You look familiar - did we have class together? I could have sworn we had chemistry.",
  "You're like a dictionary. You add meaning to my life.",
  "If you hold 8 roses in front of a mirror, you'll see 9 of the most beautiful things in the world.",
  "Is your body from McDonald's? Because I'm lovin' it.",
  "Your eyes are bluer than the Atlantic ocean and baby, I'm all lost at sea.",
  "You are so beautiful that you give the sun a reason to shine.",
  "Do you have a map? Because I just keep getting lost in your eyes.",
  "I wish I was one of your tears, so I could be born in your eyes, run down your cheek, and die on your lips.",
  "It's not my fault I fell in love. You are the one that tripped me.",
  "If you were a booger, I'd pick you first!",
  "I must be Richard Gere, because you are a Pretty Woman!"
  
}

-- XXX: Adult/R-Rated
-- User is warned prior to first use
JokerData.PickupLinesXXX = {
  "Are you a button? Cause I'd tap that!",
  "Ay gurl is yo dad in jail? Cuz if i was your dad, i’d be in jail.",
  "Are you a drill sergeant? Because you have my privates standing at attention.",
  "Your breasts remind me of Mount Rushmore – my face should be among them.",
  "Let’s play carpenter. First we’ll get hammered, then I’ll nail you.",
  "I can tell you’re into yoga, why don’t you spend a little time showing me just how flexible you are?",
  "Was your dad a baker? Because you’ve got a nice set of buns.",
  "I lost my keys… Can I check your pants?",
  "If I said you had a beautiful body, would you hold it against me?",
  "Do you know why they call me the cat whisperer? Because I know exactly what your pussy needs.",
  "I’ll be Burger King and you be McDonald’s. I’ll have it my way and you’ll be lovin’ it.",
  "You’re like my pinky toe, I’m gonna bang you on every piece of furniture in my home.",
  "Let’s go to my place and do some math. Add a bed, subtract our clothes, divide your legs, and multiply.",
  "I was feeling off today, but you definitely turned me on.",
  "I like my coffee how I like my partner... creamed.",
  "Treat me like a pirate and give me that booty.",
  "Want to save water by showering together?",
  "Are you related to Dracula? Because you looked a little thirsty when you were looking at me.",
  "So you’re not into casual sex? Fine, I’ll put on a tux and we can call it formal sex.",
  "Liquor is not the only hard thing around here.",
  "We should play strip poker. You can strip and I’ll poke you.",
  "I’m scared of getting pregnant, so do you want to go up to my room and help me test all my condoms?",
  "If you were an elevator, what button would I have to push to get you to go down?",
  "Are you butt dialing? Because I swear that ass is calling me.",
  "I’m no weather man, but you can expect more than a few inches tonight.",
  "Do you have pet insurance? Because your pussy’s getting smashed tonight.",
  "What’s the difference between a Ferrari and an erection? I don’t have a Ferrari.",
  "There are plenty of fish in the sea, but you’re the only one I’d like to catch and mount back at my place.",
  "That dress looks great on you… as a matter of fact, so would I.",
  "The only reason I would kick you out of bed would be to fuck you on the floor.",
  "Pizza is my second favorite thing to eat in bed.",
  "Why pay for a bra when I would gladly hold your boobs up all day for free?",
  "As long as I have a face, you’ll have a place to sit.",
  "Would you like to try an Australian kiss? It is just like a French kiss, but down under.",
  "Do you work for UPS? I could have sworn I saw you checking out my package.",
  "What is a nice girl like you doing in a dirty mind like mine?",
  "You can call me cake, because I’ll go straight to your ass.",
  "Are you a racehorse? Because when I ride you’ll always finish first.",
  "Fuck me if I’m wrong, but dinosaurs still exist right?",
  "I lost my virginity. Can I have yours?",
  "If I’m a pain in your ass… We can just add more lubricant.",
  "Are you my new boss? Because you just gave me a raise.",
  "Someone vacuum my lap, I think this girl needs a clean place to sit.",
  "I’m a bird watcher and I’m looking for a Big Breasted Bed Thrasher. Have you seen one?",
  "If it’s true that we are what we eat, then I could be you by morning.",
  "The last woman I was with said, 'Kiss me where it stinks.' So, I drove her to New Jersey.",
  "What's better than roses on a piano? Tulips on an organ.",
  "Wanna go back to my place and watch porn on my flat screen mirror?",
  "Screw me if I am wrong, but haven't we met before?",
  "What kind of Uber are you - long or short rides?",
  "My bed's broken, can I sleep in yours?",
  "If I told you I work for UPS, would you let me handle your package?",
  "Tell me your name so I know what to scream tonight.",
  "You look like a hard worker. I have an opening you can fill.",
  "Let's do breakfast tomorrow. Should I call you or nudge you?",
  "Did you just ring my doorbell? Well, you can come inside if you want to.",
  "I'm easy, but it looks like you're hard.",
  "That shirt is very becoming on you. Then again, I would be too!",
  "In my mind, we're going to have sex anyway, so you might as well be in the room.",
  "I don't feel so good, I think I need a shot of penis-illin.",
  "Do these look real? Wanna check?",
  "Sex is a killer. Do you wanna die happy?",
  "Let's play hockey. I'll be the net, and you can score.",
  "Do you know how to use a whip?",
  "Are you going to sleep with me or do I have to lie to my diary?",
  "If you were in bed with me, I wouldn't need the cover to keep warm.",
  "Don't stick out your tongue unless you intend to use it.",
  "Hey baby, want to play fireman? We can stop, drop, and roll.",
  "Wanna play Army? You be the enemy and I'll blow you away.",
  "I don't know what you think of me, but I hope it's X-rated.",
  "I love every bone in my body... Especially yours."
}


-- HP: Harry Potter themed
JokerData.PickupLinesHP = {
  "My name may not be Luna, but I sure know how to Lovegood.",
  "I can be your house elf. I'll do whatever you want and I don't need any clothes.",
  "My name may not be Luna, but I sure know how to Lovegood.",
  "Your smile is like Expelliarmus. Simple, but disarming.",
  "I need to learn Occlumency, because I can't get you out of my thoughts.",
  "If I were going to produce a Patronus, you'd be my happy thought.",
  "Girl, are you sure you're a muggle 'cause I'd swear that ass is magical.",
  "If you were a Dementor, I'd turn criminal just to get your kiss.",
  "Being without you is like being under the Cruciatus Curse.",
  "Are you a Snitch? Because you're by far the greatest catch here.",
  "I may not be Mad-Eye Moody, but I do have a mad eye for you.",
  "Are you using the Confundus charm or are you just naturally mind-blowing?",
  "Even if I lived in a cupboard under the stairs, I'd still make room for you.",
  "My love for you burns like a dying phoenix.",
  "You and me together? Granger things have happened!",
  "Are you a Dementor? Because you just took my breath away.",
  "Call Ollivander, because I think my wand has found its master.",
  "We may not be in Professor Flitwick's class, but you're still charming!",
  "Did you just cast Petrificus Totalus? You've made me stiff.",
  "If you were a Quaffle and I was a Chaser during a Quidditch match, I'd score with you.",
  "I'd like to get my basilisk into your Chamber of Secrets.",
  "The Sorting Hat placed me in Gryffindor. I think it's because like Godric Gryffindor himself, I too have an impressive sword.",
  "Are you interested in making some magic together? My wand is at the ready.",
  "The Sorting Hat saw my destiny, and it said I'm meant to be in your House.",
  "I don't need to cast Accio to make you come.",
  "Would you like a butterbeer? It's a Portkey. Next thing you know we'll be back at my place.",
  "I'm just like Oliver Wood, baby... I'm a keeper!",
  "I've been whomping my willow thinking about you.",
  "Speak Parseltongue to me and I’ll let my snake out.",
  "One night with me and they'll be calling you Moaning Myrtle.",
  "I don't have any muggle money, but I do have a sickle and two knuts.",
  "I might as well be under the Imperius curse, because I'd do anything for you.",
  "You know, when I said, 'Accio hottie', I didn't expect it to work!",
  "Did you put Skele-Gro in my drink? Because I can feel a bone growing!",
  "Hagrid's not the only giant on campus, if you know what I mean.",
  "I'd let you Slytherin to my bed anytime you want.",
  "You're the only thing I need in my Room of Requirement.",
  "You don't have to say Lumos to turn me on.",
  "I must have had some Felix Felicis, because I think I'm about to get lucky.",
  "Are you aware of Platform 9 and 3/4? Well, I know something else with the same definite estimations.",
  "Did you survive Avada Kedavra? Cause your drop dead gorgeous!",
  "Roses are red Violets are blue I thought Voldemort was ugly, But then I saw you. "
}
