--[[----------------------------------------------------------
	Joker - Jokes, Riddles, Fun Facts, & Other Tomfoolery
  ----------------------------------------------------------
  * VERSION: --0.0.1 ** Please do not modify this info.
  *
  * ADDING YOUR OWN JOKES:
  * Be aware that modifying this file incorrectly could break Joker,
  * so for normal users I recommend just compiling your jokes in the
  * '_MyCustomJokes.lua' file instead.
  *
  * COMPILATION: Pokemon
	*
	* SOURCES:
  * http://pickuplinesgalore.com,
  * Reddit Search, 
  * Google Search
	*
]]--

JokerData = JokerData or {}

JokerData.Pokemon = {
  "What did one Geodude say to the other Geodude? Let's rock!",
  "What is a Pokémon fan’s favorite place to go in France? Paras!",
  "Why was Hypno so energetic? He wasn’t Drowzee anymore.",
  "Which Pokémon could also be a pirate? Arrrrrr-bok.",
  "Which Pokemon does Dracula like most? Koffin'!",
  "What do you call a Pokemon who can’t move very fast? A Slow-poke.",
  "What do you call a Pokemon that wants to be a police officer? Magic-cop!",
  "Which Pokemon do soccer players like the most? GOALduck.",
  "Which college do Pokemon go to? StarU.",
  "What type of Pokemon are Jimi Hendrix, Janis Joplin and Elvis be? Legendary Pokemon",
  "What’s Pikachu’s favorite song? The Hokey Pokemon",
  "Why can’t you blindfold a Pokemon? Because it’s going to Pikachu!",
  "What do you call a low fat Pokemon? Butterfree!",
  "I asked my dad why a grown man would play Pokemon Go? He said, 'Wynaut?'",
  "Be warned, if you are in the shower, I might Pikachu. So it’s not my fault if I see any Jigglypuffs.",
  "Why shouldn’t you do drugs? Weedle make you laugh.",
  "What does an electric-type Pokémon say when they get gassy while drinking milk? I’m Zaptos intolerant!",
  "What Pokemon do people see in auctions? Bidoof.",
  "Whats the name of the Pokemon that traveled with Dorthy to Oz? Totodile.",
  "What do you call Meowth’s reflection? A copycat.",
  "How do you get Pikachu on a bus? Poke him on.",
  "What is the difference between Snorlax and a pillow? One sleeps a lot and the other gets slept on a lot!",
  "What do you call a scout that likes to chew gum while climbing Pikes Peak? A Peak-A-Chewer!",
  "What does a yellow Pokemon say before teleporting? Abra-cadabra.",
  "What do you get when you cross Pikachu with porn? Pikascrew.",
  "Why did the Miltank cross the road? To get to the other side.",
  "What TV show about dancing do pokemon love? Dancing with the Staryus.",
  "What do you call a Pikachu that can fix computers? A Geek-achu.",
  "Which sci-fi movie series do Pokemon like the most? Staryu Wars.",
  "What’s Wailmer’s favorite TV show? Whale of Fortune.",
  "Why did the Squirtle cross the ocean? To get to the other tide!",
  "Where do Haunter’s like to water ski? Lake Erie.",
  "What do you call a storm of Pokemon? A Pokemonsoon!",
  "What appears over Ash’s head when he gets an idea? A LightBulbasaur.",
  "Where did Brock take Nurse Joy for a date? The PokeBall!",
  "What do you call a daredevil Weedle who does stunts on a motorcycle? Weedle Knievell.",
  "How can pikachu make a baby laugh? By playing pika-boo!",
  "What do you do when your Loudred evolves? Buy more earplugs!",
  "What did the judge say when a Skuntank came into the court? 'Odor in the court!'",
  "I’m sorry about these bad puns, I should've kept my big meowth shut."
}

JokerData.PickupLinesPokemon = {
  "Are you a pikachu? Because you are shockingly beautiful.",
  "Do you wanna battle? 'Cuz my balls are at the ready!",
  "My love for you burns like a Charizard's tail.",
  "If I were a Nidoking, you would be my Nidoqueen.",
  "If I were a Milktank, I'd use ATTRACT on you.",
  "Looking at your ass makes my bulba soar.",
  "Want to register your number in my PokeNav?",
  "Is that a Sudowoodo in your pocket, or are you just happy to see me?",
  "I'd like to ride you like a HORSEA.",
  "When I look at you, my Metapod can't get any harder.",
  "You remind me of Pokemon, I just want to Pikachu.",
  "Do you wanna play my Poke Flute?",
  "When I'm around you, I am like a Geodude, as hard as a rock!",
  "I want to Squirtle all over your Jigglypuffs.",
  "Do you wanna play with my Poke Balls?",
  "I think I need a Paralyze Heal, because you're stunning.",
  "My Pokeballs are SWIFT in your mouth.",
  "Are you a RARE CANDY? 'cuz I feel a level-up.",
  "If you were a Pokemon, I'D CHOOSE YOU!",
  "Do you wanna LICKILICKY my icky sticky.",
  "My Donphan won't ROLLOUT for you much longer.",
  "Do you wanna see what's in my ball bag?",
  "Do you wanna see my POLI-WAG?",
  "Like an Umbreon, I also evolve at night.",
  "Can I fertilize you with my sunkern?",
  "How would you like me to use my Onix to BIND you to my bed?",
  "My Gyarados is BIG enough for you to ride it ALL day and night.",
  "I’d love to get a peek at your Rat-tatas!",
  "Hey baby, wanna SPOINK?",
  "I've got Masterballs baby.",
  "Your more beautiful than a Beautifly.",
  "Let's have a Togepi of our own!",
  "Want my Caterpie to use String Shot on you?",
  "I'd like to get in your rock tunnel.",
  "What's your favorite move? Mine is LICK.",
  "You'll be WEEZING after I'm done with you.",
  "You've got the lips of a Jynx!",
  "Can I get into YOUR Secret Base?",
  "You make my Darkrai rise.",
  "You remind me of Deoxys, you're out of this world.",
  "Those are some nice HOOTHOOTS you got there.",
  "I just want to stick it in your wooper.",
  "The name's cock..i mean brock..wait, i said that right.",
  "My Kadabra just used Future Sight, and it looks like we've got a future together.",
  "How would you like to see my viridian forest, well it's not really viridian.",
  "How about you come and see my safari zone.",
  "Want to ride my emPOLEon?",
  "You're such a good catch, i think i'll use my only MASTER BALL on you.",
  "Let's make like a Super Rod and hook up.",
  "I'm going to Hoppip into your pants.",
  "My Shellder wants to clamp onto your Slowpoke's tail!",
  "Squirtle isn't the ONLY one that can use water gun. - wink -",
  "STD’s are like Pokemon baby, gotta catch ‘em all! Wanna help me out?",
  "Do you like Pokeballs because you're about to get really close to one of mine.",
  "I wish I was a Seaking, so I could HORN DRILL you.",
  "Let's make RegiLove!",
  "Want to Link your cable onto me?",
  "I'd like to Leech my Seeds into you.",
  "You put the 'Wiggle' in Wigglytuff.",
  "Aipom's pretty good with his hands, and so am I.",
  "I wanna see your Squirtle squirt.",
  "If I was a Pokemon right now, I'd be an Erectabuzz",
  "If you were in a Pokemon Contest, you'd win first place in the Beauty/Cuteness category.",
  "I think we're going to need Defog (HM05) before the night is done.",
  "I'd like to Slowpoke your Cloyster.",
  "Are you a Hitmonlee cause your body is kickin'.",
  "My Typhlosion knows Eruption.",
  "You make me feel like an Electrode, you give me an EXPLOSION in my pants.",
  "You make me errupt like the Cinnabar Island volcano.",
  "You must be a Charmander because you're getting me hot.",
  "Let's make like the pages of this guide book and get under the covers.",
  "Baby, I'm a Mismagius. I'll make all of your wildest dreams come true.",
  "My Lickitung can reach deeper than you can imagine!",
  "Don't make me use Water Gun all over you!",
  "Are you from the Hoenn Region? 'Cuz you're the only HO I see.",
  "I wanna Munchlax your Cloyster.",
  "I'm a real Machamp, if you know what I mean.",
  "How about you use REST, so i can sleep with you.",
  "My Typhlosion knows EXPLOSION!!",
  "You put the 'Double-D' in Dodou.",
  "I heard Meowth's not the only mischievious pussy in town.",
  "Have you been taking lessons from a Lickitung?",
  "Did you just FLASH(HM 05) me?",
  "Your gonna need a HYPERPOTION by the time i'm done with you.",
  "You put the 'BONE' in Cubone.",
  "You set my Chimchar on fire.",
  "I'll use ROCK CLIMB in your Fortress.",
  "My Diglett's attracted to your SWEET SCENT.",
  "Did you use CONFUSE RAY?, cuz your making me dizzy.",
  "Do you wanna see my NUGGETS? I'd POUND you with my Piplup.",
  "You make me RY-HORNY!",
  "You just gave me a Cubone.",
  "My Bulbasaur knows TICKLE.",
  "I can make your Jigglypuffs sing.",
  "I can make your Milktanks moo.",
  "I wish you and I were Weedles, so you and I could make a Kakuna and evolve together.",
  "Hey, I've got some legendary pokemon, do you want to touch my pokeballs to see just how legendary they are?",
  "If you were a pokemon, you'd be a Squirtle, cause you make me wet!",
  "Let's go make a Mewtwo of our own.",
  "I wish I was a Magikarp, so I could use SPLASH on you!",
  "My Exeggcute are pretty weak.",
  "Let's battle so they can get some experience.",
  "Wanna watch my EKANS evolve?",
  "I made you some MOO-MOO MILK, but I forgot to use my Milktank.",
  "You make my Gyrados HYDROPUMP!",
  "I wanna spread HONEY on your Forretress.",
  "If I were a Ghastly, I'd seep right through your pants.",
  "You give my Gengar that smile.",
  "If I were a Hitmonchan, I'd Thunderpunch dat ass.",
  "Is that a TANGELA down there?",
  "Do you wanna see my BELL-SPROUT?",
  "Will you use ROCK POLISH on my Pokeballs?",
  "I wish I was an Abra, so I could TELEPORT to your bedroom.",
  "If I were a Pidgeotto, I'd GUST your pants off.",
  "It's a good thing that I'm a pokemon trainer and can handle your Jigglypuffs!",
  "If I were a Clefairy, I'd DOUBLE-SLAP dat ass.",
  "Do you have a Ditto in your pocket because I can see myself in your pants.",
  "My Magikarp knows a little more than SPLASH if you know what I mean.",
  "I like to compare myself with Smeargle...I'm pretty handy with a paintbrush.",
  "I think I'm going to need a Burn Heal because you're hot.",
  "You put the 'cool' in Tentacool.",
  "Why don't you and me go back to my gym and have a naked battle.",
  "Do you want to help my ekans learn intercourse?",
  "starMiE and starYU belong together do you get the message?",
  "I've got an Onyx, and if you come over to my place I'll show you his move Earthquake (TM 27).",
  "I wish you were the ground and I was a Diglett so I could be inside of you.",
  "Are you a Flareon? Because you're a sexy fox!",
  "I’d like to Pikachu when you’re naked!"
}
