--[[----------------------------------------------------------
	Joker - Jokes, Riddles, Fun Facts, & Other Tomfoolery
	----------------------------------------------------------
  * COMPILATION: Star Wars-related jokes
	*
	* SOURCES:
  * Reddit Search, 
  * Google Search,
  * Reader's Digest
  * inews.co.uk
  * jokes4us.com
	* 
]]--

JokerData = JokerData or {}

JokerData.StarWars = {
  "Which program do Jedi use to open PDF files? Adobe Wan Kenobi.",
  "Which website did Chewbacca get arrested for creating? Wookieleaks.",
  "Why did Anakin Skywalker cross the road? To get to the Dark Side.",
  "Why is Yoda such a good gardener? Because he has a green thumb.",
  "Why can’t you count on Yoda to pick up the tab? Because he’s always a little short.",
  "Jabba the Hut is so fat, Obi Wan took a closer look and said, 'That’s no moon.'",
  "Two Jawas walk under a bar.",
  "Luke and Obi-Wan walk into a Chinese restaurant. Ten minutes into the meal, Luke’s still having trouble with the chopsticks, dropping food everywhere. Obi-Wan finally snaps, 'Use the forks, Luke.'",
  "I’m reading a great book about Force levitation… I can’t put it down.",
  "Did you know I almost joined the Jedi Debate Team? Somebody talked me out of it.",
  "What did they call the Star Mars movie with an invisible droid? C-through-PO.",
  "What kind of car does a Jedi drive? A Toy-Yoda.",
  "Why did the movies come out 4, 5, 6, 1, 2, 3? In charge of scheduling, Yoda was.",
  "What is the internal temperature of a Tauntaun? Lukewarm.",
  "Luke: 'What’s for dinner tonight, Dad?' Anakin: 'Wookiee steak.' Luke: 'Is it any good?' Anakin: 'It’s a little chewy'",
  "What did Darth Vader say to the Emperor at the Star Wars auction? “What is thy bidding, my master?",
  "What do you get if you mix a bounty hunter with a tropical fruit? Mango Fett.",
  "Where is the best place to shop for lightsabers? The Darth Maul",
  "Why does Princess Leia keep her hair tied up in buns? So it doesn't Hang So-low.",
  "Why do Doctors make the best Jedi? Jedi must have patience.",
  "How do you unlock doors on Kashyyyk? With a woo-key.",
  "What is Jabba the Hutt’s middle name? The.",
  "What do you call Chewbacca when he chocolate stuck in his fir? A chocolate chip Wookie.",
  "What do Gungans keep things in? Jar Jars.",
  "What is a Stormtrooper’s favourite TV show? Game of Clones.",
  "What does Kylo Ren serve at a dinner party? First hors d’oeuvres.",
  "What do you call a nervous Jedi? Panickin' Skywalker.",
  "How did Darth Vader know what Luke was getting for his birthday? He felt his presents.",
  "What did Darth Vader say when he walked into a vegetarian restaurant? 'I find your lack of steak disturbing.'",
  "How did Emperor Palpatine greet Darth Vader on holidays? 'Merry Sithmas'",
  "When did Anakin's Jedi masters know he was leaning towards the dark side? While he was in the Sith Grade.",
  "What do you call a Sith who won't fight? A Sithy.",
  "What do you call a potato that has turned to the Dark side? Vader Tots.",
  "Why is a Jedi knight never lonely? Because the force is always with him.",
  "How do Ewoks communicate over long distances? With Ewokie Talkies",
  "What do you call 5 siths piled on top of a lightsaber? A Sith-Kabob!",
  "What do you call a Jedi in denial? Obi-Wan Cannot Be",
  "Why did the chicken cross the road? To get away from Kylo Hen.",
  "Which Star Wars character uses meat for a weapon instead of a Lightsaber? Obi Wan Baloney.",
  "Why is a droid mechanic never lonely? He's always making new friends!",
  "Why do Stormtroopers listen to Megan Trainor? Because 'They're all about that base, 'bout that base, no rebels.'",
  "What do you call Harrison Ford when he smokes weed? Han So-High.",
  "What do you call a Mexican jedi? Obi-Juan Kenobi",
  "How many Alderaanians does it take to change a light bulb? None, they were all destroyed by the death star. #tooSoon",
  "What do you call two suns fighting each other? Star Wars.",
  "What do you call a pirate droid? Argh2-D2",
  "Why does Padme wear buns on her head? In case she gets hungry in a Senate meeting.",
  "What do you call it when only one Star Wars character gives you a round of applause? A Hand Solo.",
  "What do you call a female Mandalorian? A Womandalorian.",
  "Why did the droid cross the road? Because it was programmed by a chicken.",
  "What do you call someone who doesn't like the dark side? Darth Hater",
  "What do you call a bounty hunter from the South? Bubba Fett",
  "What happens if Anakin Skywalker grills you a burger? It's a little on the dark side.",
  "What do Star Destroyers wear to parties? A bow TIE.",
  "Why did Kit Fisto storm out of the sushi restaurant? Because they were serving Mon Calamari.",
  "What's the differance between an ATAT and a stormtrooper? One's an Imperial walker and the other is a walking Imperial.",
  "What goes, 'Ha, ha, ha, haaaa.... AGGGHHHH! Thump'? An Imperial Officer laughing at Darth Vader.",
  "Now that Disney owns Star Wars, their next musical is expected to feature the classic, 'When You Wish Upon a Death Star'.",
  "Why is the Millenium Falcon so slow? Because it takes a millenium to go anywhere.",
  "What did Yoda say when he gave Luke Skywalker his first car? May the Porsche be with you.",
  "What happens when a red and white X-Wing crashes into green water? It gets wet.",
  "Why happened when the dog attacked the Jedi? The Jedi got darth mauled.",
  "What do you call a fight between film actors? Star Wars!",
  "What do Jawas have that no other creature in the galaxy has? Baby Jawas.",
  "What do you call a person who brings a rancor its dinner? The appetizer.",
  "Why can't a plant be on the darkside of the Force? Because it can't survive without a bit of light!",
  "What Star Wars DJ throws down the sickest beats? Fettboy Slim.",
  "Why do you call a stormtrooper in an ice cream truck? A Snow Clone.",
  "How do you get a Gungun pregnant? And you thought they were dumb!",
  "What did Luke say when he found out Darth Vader was his father? OH SITH!",
  "What's the name of the worst cantina on Coruscant? The Ackbar.",
  "How would a fat Rogue get into his X-wing? He'd Wedge himself in.",
  "How many Corellians does it take to change a glowpanel? None, if the room's dark, then you can't see them cheat at sabacc.",
  "Unless you're a Jedi and it's a lightsaber, nothing looks good hanging off your belt.",
  "You can tell a lot about somebody based on what color lightsaber they choose.",
  "If at first you don't succeed, get a lightsaber and try again.",
  "Comic Con should be on May the 4th.",
  "Sticks and Clones may break my bones, but Finn will never hurt me.",
  "I threw a stormtrooper into the lake and he sunk like a clone.",
  "I don't want to sound racist, but all stormtroopers look the same to me.",
  "Life would be better if instead of arguing, people lightsaber battled each other.",
  "You might be a redneck jedi if ... Your landspeeder has a bumper-sticker that reads 'I break for Wookies!'",
  "You might be a redneck jedi if ... Your lightsaber has been used to power a still.",
  "You might be a redneck jedi if ... You've made out with your sister and your dad wants to kill you.",
  "You might be a redneck jedi if ... You use the force to help your mother win at the bingo hall.",
  "You might be a redneck jedi if ... Your landspeeder has a blaster-rifle rack in the back window, bantha horns on the grill and a 4x4 off-road mode.",
  "You might be a redneck jedi if ... The inside of your x-wing smells worse than the outside (or inside) of a taun-taun.",
  "You might be a redneck jedi if ... You have an ewok hunting license.",
  "You might be a redneck jedi if ... Gungans can't understand 'a word yousa-say-zin.'",
  "You might be a redneck jedi if ... You have a tattoo of Obi-Wan Kenobi and under it reads 'May the Force be with y'allways.'",
  "Out of Context Quotes: 'She may not look like much, but she's got it where it counts, kid.'",
  "Out of Context Quotes: 'Curse my metal body, I wasn't fast enough!'",
  "Out of Context Quotes: 'Look at the size of that thing!'",
  "Out of Context Quotes: 'Sorry about the mess...'",
  "Out of Context Quotes: 'You came in that thing? You're braver than I thought.'",
  "Out of Context Quotes: 'Aren't you a little short for a stormtrooper?'",
  "Out of Context Quotes: 'You've got something jammed in here real good.'",
  "Out of Context Quotes: 'That's okay, I'd like to keep it on manual control for a while.'",
  "Out of Context Quotes: 'Hurry up, golden-rod...'",
  "Out of Context Quotes: 'I must've hit it pretty close to the mark to get her all riled up like that, huh kid?'",
  "Out of Context Quotes: 'Possible he came in through the south entrance.'",
  "Out of Context Quotes: 'And I thought they smelled bad on the outside!'",
  "Out of Context Quotes: 'Control, control! You must learn control!'",
  "Out of Context Quotes: 'Put that thing away before you get us all killed!'",
  "Out of Context Quotes: 'Luke, at that speed do you think you'll be able to pull out in time?'",
  "Out of Context Quotes: 'Get in there you big furry oaf, I don't care what you smell!'",
  "Where do you take a sick Tauntaun? To a Hoth-pital.",
  "What did the Sith repairman say when the client doubted he needed a new roof? Search your ceiling, you know it to be true.",
  "What do you call Chewbacca’s half-bird, half-robot pet? A Cy-porg",
  "What kind of tea do bounty hunters drink? Boba.",
  "What did Darth Vader say to his smashed wristwatch? I find your lack of face disturbing.",
  "What do you call a rebel princess who only shops at Whole Foods? Leia Organic",
  "Why couldn’t Poe Dameron find his sandwich? Because BB-8 it.",
  "Why was Rose sad while she was reading? Because she lost her Paige.",
  "Why is a gossip magazine like the Imperial Fleet? They’re both full of star destroyers.",
  "What did Han Solo say to the waiter who recommended the Haddock? Never sell me the cods!",
  "Why were the other star cruisers sad after the race? Because they lost and Rogue won.",
  "What did the Rabbi say at Anakin Skywalker’s bar mitzvah? Today you are a Manakin.",
  "How are Stormtroopers like a shark in a fight? They both end up missing a Finn.",
  "Why was Mon Mothma banned from Jedi training? She kept trying to fly into the lightsabers.",
  "What do you call Jabba the Hutt’s slave dancer when she’s in France? Oolala!",
  "How do you make stir fry on Endor? With an E-wok!",
  "What do you call Mandalorians who make smoothies a lot? Mango-lorians.",
  "What did Darth Vader say as he added salt to Lando’s soup? I am altering the meal, pray I don’t alter it any further.",
  "What do you call a Force User who lost an eye fighting a Sith? A Jed."
}
