-- * _JOKER_VERSION: 0.0.1 ** Please do not modify this line.
--[[----------------------------------------------------------
	Joker - Jokes, Riddles, Fun Facts, & Other Tomfoolery
  ----------------------------------------------------------
  *
  * ADDING YOUR OWN JOKES:
  * Be aware that modifying this file incorrectly could break Joker,
  * so for normal users I recommend just compiling your jokes in the
  * '_MyCustomJokes.lua' file instead.
  *
  * COMPILATION: Wisdom tidbits & shower thoughts (sometimes motivational, sometimes not)
	*
	* SOURCES:
  * Reddit Search, 
  * Google Search
  * Calbel (YouTube)
	*
]]--

JokerData = JokerData or {}
JokerData.Config = JokerData.Config or {}

JokerData.Config.Wisdom = {
  label = "Shower Wisdom",
  command = "wisdom",
  nsfw = false,
  joke = true,
  whitelistSlashCommand = true
}

JokerData.Wisdom = {
  "Temples are free to enter but still empty. Pubs charge to enter, but are full. People ignore inner peace & choose to pay for self destruction.",
  "Plan ahead - It wasn't raining when Noah built the ark.",
  "If you're still looking for that one person who will change your life take a look in the mirror.",
  "A diplomat is a man who always remembers a woman's birthday but never remembers her age.",
  "Learn from yesterday, live for today and have hope for tomorrow.",
  "Being an adult is just walking around wondering what you're forgetting.",
  "The road to success is always under construction.",
  "An optimist believes that we live in the best world. A pessimist is afraid that it might be true.",
  "Improve your memory by doing unforgettable things.",
  "Never laugh at your partner's choices... you're one of them.",
  "Sometimes we expect more from others because we would be willing to do that much more for them.",
  "Dont be afraid to stand for what you believe in, even if that means standing alone.",
  "A friend is like a book: you don't need to read all of them, just pick the best ones.",
  "Your life doesn't get better by chance. It gets better by choice.",
  "Can I borrow a kiss? I promise I'll give it back.",
  "Everything always ends well. If not – it's probably not the end.",
  "It's just a bad day, not a bad life.",
  "Failure is not falling down, it is not getting up again.",
  "Keep the dream alive: Hit the snooze button.",
  "The only knowledge that can hurt you is the knowledge you don't have.",
  "Whatever you do always give 100%. Unless you are donating blood.",
  "Nothing is fool proof to a sufficiently talented fool.",
  "Your Facebook friends lead much richer and more fulfilling lives than you.",
  "Mannequins don't think you're creepy.",
  "You take it the wrong way when someone says 'Don't take this the wrong way..'",
  "The GPS lady doesn't really care if you're lost.",
  "You have no gloves in your glove compartment.",
  "A wise man once said something.",
  "To avoid criticism, do nothing, say nothing, be nothing.",
  "Love thy neighbor, just don't get caught!",
  "Start everyday off with a smile. Atleast it's a good start!",
  "Don't pursue happiness - create it!",
  "Don't be pushed by your problems. Be led by your dreams.",
  "Be careful. Straight trees often have crooked roots.",
  "Always forgive your enemies. Nothing annoys them so much.",
  "No snowflake in an avalanche ever feels responsible.",
  "A ship in a harbour is safe, but that's not why ships are built.",
  "When we're young, we sneak out of home to go to parties. When we're old, we sneak out of parties to go home.",
  "The sentence 'Don't objectify women' has 'women' as the object of the sentence.",
  "In one generation we went from 'Watch your mouth around Grandma - she's from a different time', to 'Don't mind anything Grandma says, she's from a different time'.",
  "Water is a beverage whose flavor is its temperature.",
  "If reincarnation is real, maybe insects are purposely annoying because they want to get killed and come back as something better.",
  "If you're no longer covered by your parent's health insurance, then your manufacturer's warranty is over.",
  "Since there are 3600 seconds in an hour, and most people make less than $36/hr, the average person's time is worth less than a penny per second.",
  "The average person makes less than $36/hr, meaning their time is worth less than a penny per second. It's literally worth your time to pick up a penny from the ground.",
  "The first person who inhaled Helium must have been so relieved when the effects wore off.",
  "Making a typo in an online debate is the equivalent of your voice cracking in a verbal argument.",
  "If you run at 11pm you are a night person. If you run at 5am you are a morning person. If you run at 3am you are a suspicious person.",
  "By law in most countries, your vehicle must be road-worthy - yet roads don't have to be vehicle-worthy.",
  "Someone has your dream job and hates going to work everyday.",
  "The Titanic movie is like someone making a romance film out of 9/11 in 100 years.",
  "For the first 8 minutes of your life, the sunlight around you is older than you are.",
  "Your dog thinks 'fetch' is a game that the two of you made up, and he loves you for that.",
  "Virtually all of the 'tough guys' you see on TV and movies were theater majors in college.",
  "As humans were evolving, the first one to develop a sense of humour must have faced a really tough crowd.",
  "Depression is the most common mental illness, yet it somehow convinces everyone that they're completely alone.",
  "They put music from the 50s and 60s in medicine commercials to appeal to the older generations of today - meaning sometime in the future, 'Despacito' may end up playing on a commercial for laxatives.",
  "Being attracted to people who wear glasses is the one fetish for the physically impaired that's socially acceptable.",
  "Peak productivity is when one is so lazy that they do all of their work in advance so as to avoid doing it later.",
  "Maybe we *are* in a simulation, and they make a few peope actually experience a flat earth just to mess with us.",
  "Having to delete your text midway through writing it because the receiver sent another message is like getting cut off in a conversation.",
  "People say that being that one sperm out of more than a billion to reach and fertilise the egg is pretty rare and near impossible but literally everybody in this world has done it.",
  "With all the anti-intellectual movements going around, it's a surprise there are no math deniers.",
  "We have come full circle with the Egyptians who told their stories in pictures and worshiped cats.",
  "If life is a simulation, someone did a pretty good job on the character customization.",
  "Most insects have fall damage turned off.",
  "The brain is the most complex thing ever, according to the brain. So complex that it can't understand itself or it's so stupid it can't understand itself. It's like the brain has told everyone that its so complex to hide the fact that it's stupid. Which is the smartest thing the brain has ever done.",
  "Google could be lying about how many search results it found and no one would know.",
  "Those bombs with timers in movies looks like they were designed to be defused.",
  "Thor’s hammer probably rips through random people’s bodies all the time when he retrieves it from long distances.",
  "If society collapses in late December, the post apocalyptic setting will be filled with ridiculous decorations and dead trees inside people's homes.",
  "If you think someone is judging you, then you’ve just judged them.",
  "At some point you go from censoring yourself around adults to censoring yourself around children.",
  "Dogs probably think we’re immortal.",
  "If you’re afraid of the dark and you hide under your sheets, you’re completely contradicting yourself.",
  "Despite working in a fast food restaurant, Spongebob is able to afford a two story house and a pet.",
  "You don’t think anyone will enter the room until you start doing something you’re not supposed to be doing.",
  "When a professor proudly declares that most students didn't pass their class, they're proud of the fact that their expectation for their student is way higher than their actual ability to teach.",
  "Attempted murder is being accused of being a failure.",
  "Anybody that questions why you are shoveling six inches of snow in the middle of a snowstorm hasn't shoveled twelve inches of snow at the end of a snowstorm.",
  "It’s a little suspicious that seemingly 90% of books you pick up are New York Times Bestsellers.",
  "Finding the correct lid to a Tupperware container is the adult version of the baby block sorter game.",
  "Everyone talks to themselves, but it's only considered strange when you do it out loud, and in public.",
  "If you teleported to a random spot on Earth, you'd be most likely to land in the sea.",
  "A bus driver who drives the last route of the day can’t catch a bus home from work.",
  "Any piece of advice, which is vague enough, can qualify as a horoscope.",
  "If the Creator sees and watches everything, we can say he watches anime.",
  "If the Creator exists, sees and watches everything, we can say he watches anime.",
  "The car horn is the universal noise for both 'Hello' and 'F*ck You!'",
  "The more holes you put in a net, the fewer there are.",
  "You are probably in a lot of photo albums that you don't know about.",
  "Pyramid schemes are the Egyptians' curse on us for messing with their tombs.",
  "Target employees' training is technically 'Target practice'.",
  "Car junkies brag about manual transmissions. 50 years from now, they'll brag about having 'manual steering'.",
  "We perceive spies to look and dress in a certain way, but in reality, they look like normal people who fit a stereotype rather than have one.",
  "A volcano could be a one-way portal to paradise and we would never know.",
  "We can use butter knives as screwdrivers, but we can't use screwdrivers as butter knives.",
  "It's nice that, unlike many animals, our arms are long enough to reach our own genitals.",
  "You’ve probably unknowingly walked past or looked at someone who was spending their last day alive...",
  "Nobody really appreciates good water pressure before they go somewhere it sucks.",
  "If all you’re getting out of a relationship is sex you’re getting screwed.",
  "If people could preview what they COULD look like after following an exercise plan, a lot more people would stay in shape.",
  "Bullets in movies either do a whole lot of damage or none at all.",
  "Grass is kind of like the Earth’s hair.",
  "Your parents asking/urging you for grandchildren is them practically urging you to have intercourse, even though half your life they condemned you from doing exactly that.",
  "Everywhere is walking distance if you have the free time.",
  "Autocorrect in the search bar changes your mind sometimes.",
  "You could be getting stalked by the world’s best stalker and you would never find out.",
  "Attractive nurses might never get an accurate pulse reading from male patients.",
  "Humans 5000 years ago must have been really confused during a solar eclipse.",
  "Cleopatra was alive closer to the first Starbucks opening than to the building of the Great Pyramids.",
  "If gas prices keeps on increasing it will be easier to snort cocaine and run 10 miles/hour.",
  "Being a 'cold person' and being a 'warm person' are mutually exclusive. Being a 'cool person' and a 'hot person' aren’t mutually exclusive.",
  "The phrase 'we all put our pants on one leg at a time' ostrasizes the people who sit down and pull both legs on at the same time.",
  "You always think to yourself, but when you talk to yourself everyone thinks your crazy.",
  "If there are infinite universes, there exists a world where everyone has constant explosive diarrhea.",
  "The sun could have blown up seven minutes ago.",
  "Free parking almost always comes with free exercise.",
  "Your future self may be regretting a decision you are currently making.",
  "Spring is orgy season for plants.",
  "In a way, we created the first artificial dimension in the universe: The Internet.",
  "If time paused then later continued, no one would ever notice.",
  "Almost all research for new medicines is performed on mice and rats. So mice/rats are probably the species with the most effective medicines and treatments, yet they will never have access to them.",
  "Going to school is like a 13 year long tutorial in a video game - but then when you finish it, you've realized the tutorial was for a completely different game.",
  "You can get a cavity after just a few months of not brushing. But you can preserve them for centuries just by dying.",
  "We defecate in cleaner water than some nations drinking water.",
  "Receiving multiple texts instead of one paragraph is like being poked in the ribs after every sentence in a face to face conversation.",
  "It's proper etiquette to leave toilet seats down for women, but they would stay a lot cleaner if it was good manners to leave them up for men.",
  "There are more Panda Expresses in the world than there are actual pandas.",
  "The abbreviation 'lol' has deviated from it's intended purpose and become just a representation of non-aggression.",
  "People say love is blind. It's more like love sees all but doesn't give a f*ck.",
  "As we walk, we just fall and catch ourselves very fast.",
  "The month is one of the most commonly used measurements of time despite not having a specified quantity of time.",
  "If many universes exist, all art could just be photographs of those universes.",
  "Technically, WALL-E only survived through cannibalism.",
  "Your knee has never touched your ass.",
  "Reckless driving is the opposite of wreckless driving.",
  "Being a human sacrifice is a once in a lifetime opportunity.",
  "Elevators are all trust-fall exercises with the engineer's who built them.",
  "When you've been awkward with someone, it's okay because they'll walk away thinking it was them that was being awkward.",
  "The safest mode of travel is riding inside an aluminum tube going nearly the speed of sound through a layer of the atmosphere that you can't survive in.",
  "There may soon come a time when artificial intelligence is so advanced that we'll have a hard time keeping up with the news of all its scientific discoveries.",
  "One of us might've seen a real supernatural creature but all we will say is 'Wow, nice cosplay man!'",
  "Everything is edible, it's just that in most casee you'll die.",
  "Maybe dogs bring home sticks because that's what was bred into them over millennia of humans needing wood for fires.",
  "The Jedi must go through a ton of robes because they're always stripping them off before combat and just leaving them there.",
  "When you're sick, the advice you get is to do drugs and stay out of school.",
  "We use tables to keep food off the floor, table cloths to keep food off of the table, place mats to keep food off the table cloth, and plates to keep food off the place mats.",
  "Birthdays probably meant a lot more back when you weren't sure if your kid would make it through the winter.",
  "Reading a book under a tree by a warm fire seems nice to us, but for a tree it's taunting them with the shredded flesh and burnt remains of their family.",
  "Your tongue's ability to detect hair is underrated.",
  "The scariest thing we could discover on another planet would be humans.",
  "Dragons would probably think it's cool that we can create water in our mouths.",
  "300 years ago, if you had something that was made in China, everyone would be really impressed.",
  "Cheese is just a loaf of milk.",
  "Telling someone they look better with a beard is basically saying they look better the less you can see their face.",
  "That 'No alcohol beyond this point' sign might as well say, 'Bet you can't chuge that whole beer!'",
  "The phrase 'So easy a caveman could do it,' ignores the fact that cavemen were able to start fires without matches and could kill animals several times their size with nothing but very basic weaponry.",
  "The film 'Thor Ragnarok' is really about how nothing brings together two siblings like ganging up on the third one.",
  "The 'Don't text and drive' signs on the highway are probably not seen very often by their target demographic.",
  "Your debit card pays for things with past hours of your life, while your credit card pays with future hours of your life.",
  "The CEO of Starbucks technically runs one of the world's largest drug empires.",
  "The creator of Photoshop could have had a lot of fun if he didn't tell anyone.",
  "Constantly skipping a song on your favorites list is kind of like realizing you don't like a friend as much as you thought you did.",
  "Dying of old age is like dying of not dying.",
  "The voice in your head is an exceptionally good singer.",
  "Holding shift a little too long is the typed equivalent of a voice crack.",
  "The saying 'Out of sight, out of mind' does not apply when you catch a glimpse of a spider and then lose it.",
  "People would talk less trash if duels were still a thing.",
  "Horses would be way more scary if they ate meat.",
  "Translators in the UN can start a war whenever they feel like it.",
  "'X' is probably used more in mathematics than English.",
  "People with anxiety are basically way too aware of being alive.",
  "Being healthy is just the slowest possible way of dying.",
  "An argument becomes most interesting when both sides are right.",
  "People saying not to talk to them 'before their morning coffee' are basically admitting to being unpleasant when not under the influence of drugs.",
  "The thought of putting milk in a cup of water sounds horrendous until you add a coffee or tea bag into the equation.",
  "Bad things always happen to good people because when bad things happen to bad people it's a good thing.",
  "For most of everyone reading this, 2019 will probably be the last year that ends with 'teen' for the rest of our lives.",
  "People shake with their right hand as a sign of trust, with both participants immobilising their dominant hand. This makes left-handed people the most dangerous to shake hands with.",
  "It must take a while for a giraffe to throw up.",
  "Patting your pockets is like checking your inventory.",
  "They say with pessimism you'll either be correct or pleasantly surprised, but that's an awfully optimistic way to see pessimism.",
  "Anyone who says you can't buy love has never been to a pet store.",
  "If nuclear war every broke out, people on the International Space Station would probably see a hell of a show.",
  "Calling someone a 10/10 is just a nice way of calling them a 1.",
  "The person that presses the button to launch rockets must feel so satisfied. 100's or 1000's of people work on a rocket and they get to be the one that actually send it into space.",
  "Speedrunning is the art of spending an incredibly long time playing video games learning how to spend the least time playing them.",
  "If humans were ever to prove the theory that our universe is a simulation, it would simultaneously become the moment when AI became self-aware - ironically making humanity the AI all along.",
  "Instead of paying $1 for a bookmark, you could just use the dollar as a bookmark.",
  "In the Toy Story universe, a lot of people must have mysteriously died after buying horror movie merchandise.",
  "If every year was 364 days long, each day of the year would fal on the same weekday every year. But we've adopted the Gregorian calendar in a clever plot to keep selling calendars annually.",
  "Maybe Julius Caesar was right to be so arrogant - it's been over 2,000 years and everyone still knows who he is.",
  "It's impossible to say 'Stop telling people what to do' without being a hypocrite.",
  "It's funny how, as you progress through school and university, they require you to write longer and longer papers. Then you get to the professional world and noone will read an email that's more than 5 sentences.",
  "Getting consecutive green lights on your drive home is the modern equivalent of 'the winds were kind' when on a long voyage.",
  "If you curse at inanimate objects, no one cares; if you talk nicely to them, people think you're crazy.",
  "Conspiracy theorists will believe low-quality footage of UFOs, but not HD footage of rockets landing.",
  "When your dog gets to the end of its leash, it’s probably just as annoying as when you hit an invisible wall in ESO.",
  "If you catch a small fish with a big lure it's not seen as an achievement, but it probably meant a lot to that small fish to get a grip on such a big lure.",
  "Technically everything is sold for a limited time only.",
  "Life could just be hallucination that we get from inhaling oxygen.",
  "Killing a honeybee endangers their entire species around the world, yet killing a cockroach of a small family in your home doesn't do shit.",
  "If you go back and time and kill anyone famously terrible people while they were a baby or child, no one would ever know who they were. Neither would you in the future, in fact, so you would never go back to kill them, creating a paradox.",
  "When you're a kid, dick jokes are considered adult content, but when you're an adult, they're considered immature.",
  "You can film a film, but you can’t film a film.",
  "Flipbooks are the original gifs.",
  "Sleep is a drug; Bed is the dealer; Alarm clock is the cop!",
  "The Queen thinks that everywhere smells of fresh paint.",
  "Great movies spawn mediocre games. Great games spawn mediocre movies.",
}
